// Purpose: Render the Tea reference from the code that owns each surface — native catalog docs, `/** */` library docs, TSDoc, and the CLI command tree.

import {existsSync} from 'node:fs';
import {mkdir, readFile, readdir, rm, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {format} from 'prettier';
import {generateGrammar} from '../../editors/vscode/scripts/generate-syntax';
import {
  CATALOG,
  formatNativeSignature,
  formatNativeTypeRef,
  type NativeFunc,
  type NativeVar,
} from '../../src/checker/catalog';
import {
  NATIVE_FUNCTION_DOCS,
  NATIVE_VALUE_DOCS,
  type NativeValueDoc,
} from '../../src/checker/catalog-docs';
import {cliProgram} from '../../src/cli/cli';
import type {DocComment} from '../../src/syntax/doc-comments';
import {formatType, Qualifier, TypeKind} from '../../src/ir/type';
import {
  javascriptApi,
  type ApiDoc,
  type ApiExport,
  type ApiKind,
} from './javascript-api-docs';
import {
  qualifiedName,
  teaLibraries,
  type LibraryExport,
  type TeaLibrary,
} from './tea-library-docs';

const SCRIPT_FILE = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(SCRIPT_FILE), '../..');
const GENERATED =
  '{/* Generated by scripts/docs/generate-reference.ts. Do not edit by hand. */}';

// ---- page model -------------------------------------------------------------

interface ParamRow {
  readonly name: string;
  readonly type: string | null;
  readonly defaultValue: string | null;
  readonly description: string;
}

/** A documented class or interface member, shown under its owner. */
interface Subsection {
  readonly name: string;
  readonly signature: string;
  readonly text: string;
}

interface Entry {
  /** As code writes it: `ta.sma`, `trade.NextOpenTrade`, `tea run`. */
  readonly name: string;
  /**
   * The page heading. Mintlify and Docusaurus slug punctuation differently
   * (`ta.sma` becomes `ta-sma` in one and `tasma` in the other) and neither
   * reads explicit ids from both, so headings hold only letters, digits, `_`
   * and spaces: the name within its page's namespace, `sma` on the `ta` page.
   * Empty for a table that sits directly under its category heading.
   */
  readonly heading: string;
  /** Names a `{@link …}` resolves to this entry. */
  readonly symbols: readonly string[];
  readonly summary: string;
  readonly signature: string | null;
  readonly params: readonly ParamRow[];
  readonly returns: string | null;
  /** One table row per member: its declaration, value or name, then notes. */
  readonly table: {
    readonly columns: readonly string[];
    readonly rows: readonly (readonly string[])[];
  } | null;
  readonly body: string;
  readonly subsections: readonly Subsection[];
  readonly category: string;
}

interface Page {
  readonly route: string;
  readonly title: string;
  readonly description: string;
  readonly intro: string;
  readonly language: 'tea' | 'ts' | 'bash';
  readonly scope: 'tea' | 'javascript';
  /** What the parameter table calls its rows: `Parameter` or `Argument`. */
  readonly paramLabel: string;
  readonly entries: readonly Entry[];
  /** Parameters documented once for the page instead of on every entry. */
  readonly shared: readonly ParamRow[];
}

function entry(
  fields: Partial<Entry> & Pick<Entry, 'name' | 'summary' | 'category'>,
): Entry {
  return {
    heading: fields.name.slice(fields.name.lastIndexOf('.') + 1),
    symbols: [fields.name],
    signature: null,
    params: [],
    returns: null,
    table: null,
    body: '',
    subsections: [],
    ...fields,
  };
}

// ---- built-in pages ---------------------------------------------------------

interface BuiltinPage {
  readonly slug: string;
  readonly title: string;
  readonly description: string;
  readonly intro: string;
  readonly natives: (name: string) => boolean;
  readonly library?: string;
  readonly shared?: readonly string[];
}

const namespace =
  (...names: string[]) =>
  (name: string) =>
    names.some(prefix => name.startsWith(`${prefix}.`));

const METHOD_FORM =
  'Every function whose first parameter is `self` can also be called as a method on the collection: `values.push(x)` is the same call as `array.push(values, x)`.';

const BUILTIN_PAGES: readonly BuiltinPage[] = [
  {
    slug: 'core',
    title: 'Core functions',
    description: 'Missing values, conversions and script declarations.',
    intro: 'Global functions available in every script without a namespace.',
    natives: name =>
      [
        'na',
        'nz',
        'int',
        'float',
        'str.tostring',
        'indicator',
        'library',
      ].includes(name),
  },
  {
    slug: 'input',
    title: 'input',
    description: 'Script inputs a host can set without editing the source.',
    intro:
      'An input declares a value the host supplies when it binds the script, falling back to the default written in the source. {@link input} explains how inputs are named and when their values are fixed.',
    natives: name => name === 'input' || name.startsWith('input.'),
    shared: [
      'title',
      'tooltip',
      'inline',
      'group',
      'confirm',
      'display',
      'active',
    ],
  },
  {
    slug: 'math',
    title: 'math',
    description: 'Arithmetic helpers and mathematical constants.',
    intro: 'Functions and constants in the `math` namespace.',
    natives: namespace('math'),
  },
  {
    slug: 'color',
    title: 'color',
    description: 'Color construction and Tea’s standard palette.',
    intro: 'Functions and constants in the `color` namespace.',
    natives: namespace('color'),
  },
  {
    slug: 'array',
    title: 'array',
    description: 'Functions for ordered, variable-length collections.',
    intro: `See [types](../language/types.md) for the \`array<T>\` type and [memory model](/memory-model) for how array values are copied and shared. ${METHOD_FORM}`,
    natives: namespace('array'),
  },
  {
    slug: 'matrix',
    title: 'matrix',
    description: 'Functions for two-dimensional collections.',
    intro: `See [types](../language/types.md) for the \`matrix<T>\` type and [memory model](/memory-model) for how matrix values are copied and shared. ${METHOD_FORM}`,
    natives: namespace('matrix'),
  },
  {
    slug: 'map',
    title: 'map',
    description: 'Functions for key-value collections.',
    intro: `See [types](../language/types.md) for the \`map<K, V>\` type and [memory model](/memory-model) for how map values are copied and shared. ${METHOD_FORM}`,
    natives: namespace('map'),
  },
  {
    slug: 'request',
    title: 'request',
    description: 'Calculations evaluated in another symbol or timeframe.',
    intro:
      'A request evaluates an expression in a child context fed by its own data stream. [Requests](/requests) explains binding and synchronization in depth.',
    natives: namespace('request'),
  },
  {
    slug: 'market-data',
    title: 'Market data',
    description:
      'Prices, bar and time values, symbol and timeframe information, and bar state.',
    intro:
      'Values the host supplies for the current bar, available in every script without an import. Each entry says what it holds inside a request.',
    library: 'pine',
    natives: name =>
      ['bar_index', 'time', 'timenow'].includes(name) ||
      namespace('syminfo', 'timeframe', 'barstate')(name),
  },
  {
    slug: 'plots',
    title: 'Plots and alerts',
    description: 'Named chart outputs, alerts and their style constants.',
    intro:
      'Each call writes one named output that a host can draw or deliver. See [outputs and events](/language-guide/outputs-and-events).',
    library: 'visual',
    natives: namespace(
      'plot',
      'hline',
      'location',
      'shape',
      'size',
      'display',
      'format',
      'position',
    ),
  },
  {
    slug: 'ta',
    title: 'ta',
    description: 'Technical-analysis functions written in Tea.',
    intro: '',
    library: 'ta',
    natives: () => false,
  },
];

const isLiteral = (value: NativeVar) =>
  value.qualifier === Qualifier.Const && !value.name.includes('.');

function qualifierType(qualifier: string, type: string): string {
  return `${qualifier} ${type}`;
}

/**
 * Facts the catalog states about a parameter, as reader-facing notes. A note
 * appears only when every overload agrees: `input(close)` takes a series even
 * though the other `input` overloads need a constant `defval`.
 */
function parameterNotes(
  overloads: readonly NativeFunc[],
  name: string,
): string {
  const params = overloads.flatMap(overload =>
    overload.params.filter(param => param.name === name),
  );
  const notes: string[] = [];
  if (params.every(param => param.constLiteral)) {
    notes.push('Must be a compile-time constant.');
  }
  if (
    params.every(param => !param.acceptsNa) &&
    params.every(
      param =>
        typeof param.type === 'string' || param.type.kind !== TypeKind.Bool,
    )
  ) {
    notes.push('Cannot be `na`.');
  }
  if (params.every(param => param.mode === 'inout')) {
    notes.push('Must be a variable or field; the call updates it.');
  }
  if (params.every(param => param.capture)) {
    notes.push('Evaluated in the requested context.');
  }
  return notes.join(' ');
}

function nativeParams(
  name: string,
  overloads: readonly NativeFunc[],
): ParamRow[] {
  const doc = NATIVE_FUNCTION_DOCS[name]!;
  const order: string[] = [];
  const types = new Map<string, Set<string>>();
  for (const overload of overloads) {
    for (const param of overload.params) {
      if (param.availability !== 'supported') continue;
      if (!types.has(param.name)) {
        order.push(param.name);
        types.set(param.name, new Set());
      }
      types
        .get(param.name)!
        .add(
          qualifierType(param.qualifierCap, formatNativeTypeRef(param.type)),
        );
    }
  }
  return order.map(param => {
    const prose = doc.params[param];
    if (prose === undefined) {
      throw new Error(
        `native function ${name} does not document parameter ${param}`,
      );
    }
    const notes = parameterNotes(overloads, param);
    return {
      name: param,
      type: [...types.get(param)!].join(', '),
      defaultValue: null,
      description: notes === '' ? prose : `${prose} ${notes}`,
    };
  });
}

function nativeFunctionEntry(
  name: string,
  overloads: readonly NativeFunc[],
): Entry {
  const doc = NATIVE_FUNCTION_DOCS[name];
  if (doc === undefined)
    throw new Error(`native function ${name} has no documentation`);
  return entry({
    name,
    summary: doc.summary,
    signature: overloads.map(formatNativeSignature).join('\n'),
    params: nativeParams(name, overloads),
    returns: doc.returns ?? null,
    body: joinBlocks(doc.details, fence(doc.example)),
    category: doc.category,
  });
}

function valueSignature(value: NativeVar): string {
  const declared = `${value.qualifier} ${formatType(value.type)} ${value.name}`;
  return value.qualifier === Qualifier.Const
    ? `${declared} = ${formatConstant(value)}`
    : declared;
}

function formatConstant(value: NativeVar): string {
  if (typeof value.value === 'string' && value.type.kind === TypeKind.String) {
    return JSON.stringify(value.value);
  }
  return String(value.value);
}

function valueEntries(values: readonly NativeVar[]): Entry[] {
  const entries: Entry[] = [];
  const families = new Set<string>();
  for (const value of values) {
    const key = Object.keys(NATIVE_VALUE_DOCS).find(candidate =>
      candidate.endsWith('*')
        ? value.name.startsWith(candidate.slice(0, -1))
        : candidate === value.name,
    );
    if (key === undefined)
      throw new Error(`native value ${value.name} has no documentation`);
    const doc: NativeValueDoc = NATIVE_VALUE_DOCS[key]!;
    if (!key.endsWith('*')) {
      entries.push(
        entry({
          name: value.name,
          summary: doc.summary,
          signature: valueSignature(value),
          body: joinBlocks(doc.details, fence(doc.example)),
          category: doc.category,
        }),
      );
      continue;
    }
    if (families.has(key)) continue;
    families.add(key);
    const members = values.filter(member =>
      member.name.startsWith(key.slice(0, -1)),
    );
    const notes = members.some(
      member => doc.members?.[member.name] !== undefined,
    );
    entries.push(
      entry({
        name: key,
        // `plot.style_*` reads "plot style"; `color.*` reads "color".
        heading: key.replace(/[*._]+$/, '').replaceAll('.', ' '),
        symbols: members.map(member => member.name),
        summary: doc.summary,
        table: {
          columns: notes
            ? ['Constant', 'Value', 'Description']
            : ['Constant', 'Value'],
          rows: members.map(member => [
            code(member.name),
            code(formatConstant(member)),
            ...(notes ? [doc.members?.[member.name] ?? ''] : []),
          ]),
        },
        body: joinBlocks(
          `Each constant is a ${code(`const ${formatType(members[0]!.type)}`)}.`,
          doc.details,
          fence(doc.example),
        ),
        category: doc.category,
      }),
    );
  }
  return entries;
}

function builtinPages(libraries: readonly TeaLibrary[]): Page[] {
  const values = [...CATALOG.vars.values()].filter(value => !isLiteral(value));
  const placed = new Map<string, string>();
  const place = (name: string, slug: string) => {
    const previous = placed.get(name);
    if (previous !== undefined) {
      throw new Error(`${name} belongs to both ${previous} and ${slug} pages`);
    }
    placed.set(name, slug);
  };
  const pages = BUILTIN_PAGES.map(config => {
    const library =
      config.library === undefined
        ? undefined
        : libraries.find(candidate => candidate.name === config.library)!;
    const functions = [...CATALOG.funcs].filter(([name]) =>
      config.natives(name),
    );
    const pageValues = values.filter(value => config.natives(value.name));
    for (const [name] of functions) place(name, config.slug);
    for (const value of pageValues) place(value.name, config.slug);
    const entries = [
      ...(library === undefined ? [] : libraryEntries(library)),
      ...functions.map(([name, overloads]) =>
        nativeFunctionEntry(name, overloads),
      ),
      ...valueEntries(pageValues),
    ];
    return finishShared(
      {
        route: `reference/builtins/${config.slug}`,
        title: config.title,
        description: config.description,
        intro: joinBlocks(
          config.intro,
          library === undefined ? undefined : libraryIntro(library),
        ),
        language: 'tea',
        scope: 'tea',
        paramLabel: 'Parameter',
        entries,
        shared: [],
      },
      config.shared ?? [],
    );
  });
  const unplaced = [
    ...[...CATALOG.funcs.keys()],
    ...values.map(value => value.name),
  ].filter(name => !placed.has(name));
  if (unplaced.length > 0) {
    throw new Error(`no reference page holds: ${unplaced.join(', ')}`);
  }
  return pages;
}

/** Move parameters documented identically on every entry into one table. */
function finishShared(page: Page, names: readonly string[]): Page {
  if (names.length === 0) return page;
  const shared = new Map<string, ParamRow>();
  const entries = page.entries.map(item => {
    const own = item.params.filter(param => !names.includes(param.name));
    const common = item.params.filter(param => names.includes(param.name));
    for (const param of common) {
      const previous = shared.get(param.name);
      if (
        previous !== undefined &&
        previous.description !== param.description
      ) {
        throw new Error(
          `${page.title}: parameter ${param.name} must read the same on every entry (${item.name})`,
        );
      }
      if (previous !== undefined && previous.type !== param.type) {
        shared.set(param.name, {
          ...previous,
          type: `${previous.type}, ${param.type}`,
        });
      } else if (previous === undefined) {
        shared.set(param.name, param);
      }
    }
    const also =
      common.length === 0
        ? ''
        : `Also accepts the [common parameters](#common-parameters) ${common.map(param => code(param.name)).join(', ')}.`;
    return {...item, params: own, body: joinBlocks(also, item.body)};
  });
  return {
    ...page,
    entries,
    shared: names.flatMap(name =>
      shared.has(name) ? [shared.get(name)!] : [],
    ),
  };
}

// ---- library pages ----------------------------------------------------------

function libraryIntro(library: TeaLibrary): string {
  if (library.doc === null)
    throw new Error(`${library.file}: library() has no doc comment`);
  const access =
    library.access === 'global'
      ? 'Available in every script without an import or namespace.'
      : library.access === 'namespace'
        ? `Available in every script as ${code(`${library.name}.name`)} without an import.`
        : `Add ${code(`import ${library.name}`)} to a script to use these as ${code(`${library.name}.name`)}.`;
  return joinBlocks(library.doc.summary, library.doc.body, access);
}

function memberText(doc: DocComment | null, where: string): string {
  if (doc === null) throw new Error(`${where} has no doc comment`);
  if (doc.body.includes('```')) {
    throw new Error(
      `${where}: member docs render in a table and cannot hold examples`,
    );
  }
  return [
    doc.summary,
    doc.body,
    ...[...doc.params].map(
      ([name, text]) => `${code(name)}: ${punctuate(text)}`,
    ),
    doc.returns === null ? '' : `Returns: ${punctuate(doc.returns)}`,
  ]
    .filter(part => part !== '')
    .join(' ');
}

function librarySignature(library: TeaLibrary, item: LibraryExport): string {
  if (item.kind !== 'function') return item.declaration;
  const params = item.params.map(
    param =>
      `${param.type === null ? '' : `${param.type} `}${param.name}${param.defaultValue === null ? '' : ` = ${param.defaultValue}`}`,
  );
  const name = qualifiedName(library, item.name);
  const single = `${name}(${params.join(', ')})`;
  return single.length <= 80
    ? single
    : `${name}(\n${params.map(param => `    ${param},`).join('\n')}\n)`;
}

// Readers start from what they call, then read the types those calls use.
const READING_ORDER: Readonly<Record<LibraryExport['kind'], number>> = {
  function: 0,
  value: 0,
  type: 1,
  enum: 1,
  interface: 1,
};

function libraryEntries(library: TeaLibrary): Entry[] {
  const exports = [...library.exports].sort(
    (a, b) => READING_ORDER[a.kind] - READING_ORDER[b.kind],
  );
  return exports.map(item => {
    const where = `${library.file}:${item.line} ${item.name}`;
    const doc = item.doc;
    if (doc === null) throw new Error(`${where} has no doc comment`);
    return entry({
      name: qualifiedName(library, item.name),
      heading: item.name,
      summary: doc.summary,
      signature: librarySignature(library, item),
      params: item.params.map(param => {
        const description = doc.params.get(param.name);
        if (description === undefined) {
          throw new Error(`${where} does not document parameter ${param.name}`);
        }
        return {...param, description};
      }),
      returns: doc.returns,
      table:
        item.members.length === 0
          ? null
          : {
              columns: ['Member', 'Description'],
              rows: item.members.map(member => [
                code(member.declaration),
                memberText(
                  member.doc,
                  `${library.file}:${member.line} ${item.name}.${member.name}`,
                ),
              ]),
            },
      body: doc.body,
      category: doc.category ?? 'Declarations',
    });
  });
}

function libraryPages(libraries: readonly TeaLibrary[]): Page[] {
  return libraries
    .filter(library => library.access === 'import')
    .map(library => ({
      route: `reference/libraries/${library.name}`,
      title: library.name,
      description: library.doc?.summary ?? '',
      intro: libraryIntro(library),
      language: 'tea',
      scope: 'tea',
      paramLabel: 'Parameter',
      entries: libraryEntries(library),
      shared: [],
    }));
}

// ---- JavaScript API pages ---------------------------------------------------

const API_CATEGORIES: Readonly<Record<ApiKind, string>> = {
  function: 'Functions',
  class: 'Classes',
  interface: 'Interfaces',
  type: 'Types',
  enum: 'Enums',
  constant: 'Constants',
};

function splitSummary(text: string): {summary: string; rest: string} {
  const [summary = '', ...rest] = text.trim().split(/\n\s*\n/);
  return {summary: summary.replace(/\s*\n\s*/g, ' '), rest: rest.join('\n\n')};
}

function firstSentence(text: string): string {
  return /^.+?[.!?](?=\s|$)/.exec(text)?.[0] ?? text;
}

/**
 * TSDoc examples are Markdown: fenced code stays as written, a sentence with
 * inline code reads as prose, and bare code gets a fence.
 */
function apiExamples(doc: ApiDoc): string {
  return doc.examples
    .map(example =>
      example.includes('```')
        ? example
        : example.includes('`')
          ? `**Example:** ${example}`
          : fence(example, 'ts')!,
    )
    .join('\n\n');
}

function apiEntry(item: ApiExport, heading: string): Entry {
  const {summary, rest} = splitSummary(item.doc.text);
  return entry({
    name: item.name,
    heading,
    summary,
    signature: item.signature,
    params: [...item.doc.params].map(([name, text]) => ({
      name,
      type: null,
      defaultValue: null,
      description: text,
    })),
    returns: item.doc.returns,
    body: joinBlocks(rest, apiExamples(item.doc)),
    symbols: [
      item.name,
      ...item.members.map(member => `${item.name}.${member.name}`),
    ],
    subsections: item.members.map(member => ({
      name: `${item.name}.${member.name}`,
      signature: member.signature,
      text: joinBlocks(
        member.doc.text,
        member.doc.params.size === 0
          ? undefined
          : [...member.doc.params]
              .map(([name, text]) => `- ${code(name)}: ${text}`)
              .join('\n'),
        member.doc.returns === null
          ? undefined
          : `**Returns:** ${member.doc.returns}`,
        apiExamples(member.doc),
      ),
    })),
    category: API_CATEGORIES[item.kind],
  });
}

function javascriptPages(): Page[] {
  return javascriptApi().map(api => {
    const order = Object.keys(API_CATEGORIES);
    const exports = [...api.exports].sort(
      (a, b) =>
        order.indexOf(a.kind) - order.indexOf(b.kind) ||
        a.name.localeCompare(b.name),
    );
    const headed = exports.filter(item => !isTableConstant(item));
    // Headings slug case-insensitively, but `Color` and `color` are two
    // exports: such names carry their kind, "Color class" and "color function".
    const folded = headed.map(item => item.name.toLowerCase());
    const description = splitSummary(api.description ?? '');
    return {
      route: `reference/javascript/${api.specifier === 'tea' ? 'tea' : api.specifier.slice(4).replaceAll('/', '-')}`,
      title: api.specifier,
      description: firstSentence(description.summary),
      intro: joinBlocks(
        `\`\`\`ts\nimport {…} from '${api.specifier}';\n\`\`\``,
        description.summary,
        description.rest,
      ),
      language: 'ts',
      scope: 'javascript',
      paramLabel: 'Parameter',
      shared: [],
      entries: [
        ...headed.map(item =>
          apiEntry(
            item,
            folded.filter(name => name === item.name.toLowerCase()).length > 1
              ? `${item.name} ${item.kind}`
              : item.name,
          ),
        ),
        ...constantTable(exports),
      ],
    };
  });
}

/** A constant whose whole story is one declaration line and a sentence or two. */
function isTableConstant(item: ApiExport): boolean {
  return (
    item.kind === 'constant' &&
    !item.signature.includes('\n') &&
    item.doc.examples.length === 0
  );
}

/** One-line constants, such as the clock units `ms` and `M`, read best as one table. */
function constantTable(exports: readonly ApiExport[]): Entry[] {
  const constants = exports.filter(isTableConstant);
  if (constants.length === 0) return [];
  return [
    entry({
      name: 'Constants',
      heading: '',
      symbols: constants.map(item => item.name),
      summary: '',
      table: {
        columns: ['Constant', 'Declaration', 'Description'],
        rows: constants.map(item => [
          code(item.name),
          code(item.signature.replace(/;$/, '')),
          item.doc.text,
        ]),
      },
      category: API_CATEGORIES.constant,
    }),
  ];
}

// ---- CLI page ---------------------------------------------------------------

function cliPage(): Page {
  const program = cliProgram(() => {});
  const entries = program.commands.map(command => {
    const usage = `tea ${command.name()} ${command.usage()}`.trim();
    const args = command.registeredArguments.map(argument => ({
      name: argument.name(),
      type: null,
      defaultValue: null,
      description: `${sentence(argument.description)}${argument.required ? '' : ' Optional.'}`,
    }));
    const options = command.options.map(option => {
      const fallback =
        option.negate || option.defaultValue === undefined
          ? ''
          : ` Default: ${option.defaultValueDescription ?? code(String(option.defaultValue))}.`;
      return [
        code(option.flags),
        `${sentence(option.description)}${fallback}${option.mandatory ? ' Required.' : ''}`,
      ];
    });
    const summary = punctuate(command.summary() || command.description());
    const description = punctuate(command.description());
    return entry({
      name: `tea ${command.name()}`,
      heading: `tea ${command.name()}`,
      summary,
      body: description === summary ? '' : description,
      signature: usage,
      params: args,
      table:
        options.length === 0
          ? null
          : {columns: ['Option', 'Description'], rows: options},
      category: 'Commands',
    });
  });
  return {
    route: 'reference/tools/cli',
    title: 'tea command',
    description: punctuate(program.description()),
    intro:
      'The `tea` command compiles, runs and inspects Tea scripts, serves this documentation offline, and runs the language server. Every command accepts `--help`; `tea --version` prints the version. Set the `TEA_LOG` environment variable to `debug`, `info`, `warn` or `error` to change how much the command logs.',
    language: 'bash',
    scope: 'tea',
    paramLabel: 'Argument',
    entries,
    shared: [],
  };
}

// ---- rendering --------------------------------------------------------------

function code(value: string): string {
  const ticks = value.includes('`') ? '``' : '`';
  return `${ticks}${value}${ticks}`;
}

function fence(
  source: string | undefined,
  language = 'tea',
): string | undefined {
  return source === undefined
    ? undefined
    : `\`\`\`${language}\n${source}\n\`\`\``;
}

function joinBlocks(...blocks: readonly (string | undefined)[]): string {
  return blocks
    .filter(block => block !== undefined && block.trim() !== '')
    .join('\n\n');
}

function punctuate(text: string): string {
  return /[.!?]$/.test(text) ? text : `${text}.`;
}

/** Commander help reads `port to bind`; reference tables read sentences. */
function sentence(text: string): string {
  return punctuate(text.charAt(0).toUpperCase() + text.slice(1));
}

/** The slug both renderers give a heading of letters, digits, `_` and spaces. */
function slug(heading: string): string {
  if (!/^[A-Za-z0-9_ ]+$/.test(heading)) {
    throw new Error(
      `heading '${heading}' must hold only letters, digits, _ and spaces`,
    );
  }
  return heading.toLowerCase().replaceAll(' ', '-');
}

function categories(page: Page): Map<string, Entry[]> {
  const grouped = new Map<string, Entry[]>();
  for (const item of page.entries) {
    const list = grouped.get(item.category) ?? [];
    list.push(item);
    grouped.set(item.category, list);
  }
  return grouped;
}

interface Target {
  readonly route: string;
  readonly anchor: string;
}

/**
 * Every symbol's anchor on its page. Duplicate slugs are an error because the
 * renderers number repeated headings differently.
 */
function anchors(page: Page): Map<string, string> {
  const symbols = new Map<string, string>();
  const slugs = new Set<string>();
  const claim = (heading: string) => {
    const id = slug(heading);
    if (slugs.has(id))
      throw new Error(`${page.route}: two headings read '${heading}'`);
    slugs.add(id);
    return id;
  };
  if (page.shared.length > 0) claim('Common parameters');
  for (const [category, items] of categories(page)) {
    const categoryId = claim(category.replace(/[^A-Za-z0-9_ ]/g, ''));
    for (const item of items) {
      const id = item.heading === '' ? categoryId : claim(item.heading);
      for (const symbol of item.symbols) symbols.set(symbol, id);
    }
  }
  return symbols;
}

type SymbolIndex = ReadonlyMap<string, Target>;

const LINK = /\{@link\s+([^\s}|]+)(?:\s*\|\s*([^}]+?))?\s*\}/g;

/** Resolve `{@link name}` and `{@link name | label}`, then guard MDX syntax. */
function prose(text: string, index: SymbolIndex, page: Page): string {
  const resolved = text.replace(
    LINK,
    (_, target: string, label: string | undefined) => {
      const found = index.get(target);
      if (found === undefined) {
        if (page.scope === 'tea') {
          throw new Error(
            `${page.route}: {@link ${target}} names no documented symbol`,
          );
        }
        return code(label ?? target);
      }
      const href = `/${found.route}#${found.anchor}`;
      return `[${code(label ?? target)}](${href})`;
    },
  );
  return escapeMdx(resolved);
}

/** A page description as plain text for front matter: no links, no code marks. */
function plainText(text: string): string {
  return text
    .replace(
      LINK,
      (_, target: string, label: string | undefined) => label ?? target,
    )
    .replaceAll('`', '');
}

/** A description inside another page, where links become code. */
function linkless(text: string): string {
  return escapeMdx(
    text.replace(LINK, (_, target: string, label: string | undefined) =>
      code(label ?? target),
    ),
  );
}

/** Escape `<`, `{` and `}` outside code, where MDX would read JSX. */
function escapeMdx(markdown: string): string {
  return markdown
    .split(/(```[\s\S]*?```|`[^`\n]*`)/g)
    .map((part, index) =>
      index % 2 === 1
        ? part
        : part.replace(/[<{}]/g, character => `\\${character}`),
    )
    .join('');
}

function cell(markdown: string): string {
  return markdown.replace(/\s*\n\s*/g, ' ').replace(/\|/g, '\\|');
}

function table(
  columns: readonly string[],
  rows: readonly (readonly string[])[],
): string {
  return [
    `| ${columns.join(' | ')} |`,
    `| ${columns.map(() => '---').join(' | ')} |`,
    ...rows.map(row => `| ${row.map(cell).join(' | ')} |`),
  ].join('\n');
}

function paramTable(
  params: readonly ParamRow[],
  index: SymbolIndex,
  page: Page,
): string {
  const typed = params.some(param => param.type !== null);
  const defaults = params.some(param => param.defaultValue !== null);
  return table(
    [
      page.paramLabel,
      ...(typed ? ['Type'] : []),
      ...(defaults ? ['Default'] : []),
      'Description',
    ],
    params.map(param => [
      code(param.name),
      ...(typed ? [param.type === null ? '' : code(param.type)] : []),
      ...(defaults
        ? [param.defaultValue === null ? '' : code(param.defaultValue)]
        : []),
      prose(param.description, index, page),
    ]),
  );
}

function renderPage(page: Page, index: SymbolIndex): string {
  const grouped = categories(page);
  const summaryTable =
    page.entries.length > 3
      ? table(
          ['Name', 'Description'],
          [...grouped.values()]
            .flat()
            .filter(item => item.heading !== '')
            .map(item => [
              `[${code(item.name)}](#${slug(item.heading)})`,
              prose(item.summary, index, page),
            ]),
        )
      : undefined;
  const shared =
    page.shared.length === 0
      ? undefined
      : `## Common parameters\n\n${paramTable(page.shared, index, page)}`;
  const sections = [...grouped].map(([category, items]) =>
    joinBlocks(
      `## ${category}`,
      ...items.map(item =>
        joinBlocks(
          item.heading === '' ? undefined : `### ${item.heading}`,
          prose(item.summary, index, page),
          fence(item.signature ?? undefined, page.language),
          item.params.length === 0
            ? undefined
            : paramTable(item.params, index, page),
          item.returns === null
            ? undefined
            : `**Returns:** ${prose(item.returns, index, page)}`,
          item.table === null
            ? undefined
            : table(
                item.table.columns,
                item.table.rows.map(row =>
                  row.map(value => prose(value, index, page)),
                ),
              ),
          prose(item.body, index, page),
          ...item.subsections.map(subsection =>
            joinBlocks(
              `**${code(subsection.name)}**`,
              fence(subsection.signature, 'ts'),
              prose(subsection.text, index, page),
            ),
          ),
        ),
      ),
    ),
  );
  return joinBlocks(
    `---\ntitle: ${JSON.stringify(page.title)}\ndescription: ${JSON.stringify(plainText(page.description))}\n---`,
    GENERATED,
    prose(page.intro, index, page),
    summaryTable,
    shared,
    ...sections,
  );
}

// ---- overview ---------------------------------------------------------------

interface NavigationGroup {
  readonly group: string;
  readonly pages: readonly (string | NavigationGroup)[];
}

interface DocsJson {
  readonly navigation: {
    readonly tabs: readonly {
      readonly tab: string;
      readonly groups: readonly NavigationGroup[];
    }[];
  };
}

function frontMatter(text: string, key: string): string {
  const value = new RegExp(`^${key}:\\s*(.+?)\\s*$`, 'm').exec(text)?.[1] ?? '';
  return /^["']/.test(value)
    ? (JSON.parse(value.replace(/^'|'$/g, '"')) as string)
    : value;
}

/**
 * The overview lists the Reference tab of docs.json, which owns navigation.
 * A generated page missing from it, or a listed page that does not exist,
 * fails generation.
 */
async function overviewPage(
  root: string,
  pages: readonly Page[],
): Promise<string> {
  const docs = JSON.parse(
    await readFile(path.join(root, 'docs/docs.json'), 'utf8'),
  ) as DocsJson;
  const tab = docs.navigation.tabs.find(
    candidate => candidate.tab === 'Reference',
  );
  if (tab === undefined) throw new Error('docs.json has no Reference tab');
  const generated = new Map(pages.map(page => [page.route, page]));
  const listed = new Set<string>();
  const sections: string[] = [];
  for (const group of tab.groups) {
    const rows: string[][] = [];
    for (const route of group.pages) {
      if (typeof route !== 'string')
        throw new Error('Reference navigation is one level deep');
      listed.add(route);
      if (route === 'reference/overview') continue;
      const page = generated.get(route);
      let title = page?.title;
      let description = page?.description;
      if (page === undefined) {
        const file = path.join(root, 'docs', `${route}.md`);
        if (!existsSync(file))
          throw new Error(`docs.json lists missing page ${route}`);
        const text = await readFile(file, 'utf8');
        title = frontMatter(text, 'title');
        description = frontMatter(text, 'description');
      }
      rows.push([`[${title}](/${route})`, linkless(description ?? '')]);
    }
    if (rows.length > 0) {
      sections.push(`## ${group.group}`, table(['Page', 'Covers'], rows));
    }
  }
  const unlisted = pages
    .filter(page => !listed.has(page.route))
    .map(page => page.route);
  if (unlisted.length > 0) {
    throw new Error(
      `docs.json does not list generated pages: ${unlisted.join(', ')}`,
    );
  }
  return joinBlocks(
    '---\ntitle: "Reference"\ndescription: "Exact lookup documentation for the Tea language, its built-ins and libraries, the tea command and the JavaScript API."\n---',
    GENERATED,
    'Use the Reference to look up exact syntax and behavior. If you are learning Tea, start with the Documentation tab.',
    '## Reading signatures',
    'Built-in signatures read `name(param: type, optional?: type, ...rest: type) → result`. Parameter tables add the qualifier each argument may have — `const`, `input`, `simple` or `series`, from least to most variable — and any further requirement, such as a compile-time constant. Functions written in Tea, such as `ta` and the libraries, show their declaration as written; a parameter without a type accepts any argument the function body can use. See [Types and qualifiers](/reference/language/types).',
    ...sections,
  );
}

// ---- outputs ----------------------------------------------------------------

function symbolIndex(
  pages: readonly Page[],
  scope: Page['scope'],
): Map<string, Target> {
  const index = new Map<string, Target>();
  for (const page of pages.filter(candidate => candidate.scope === scope)) {
    for (const [symbol, anchor] of anchors(page)) {
      if (index.has(symbol)) {
        // One JavaScript declaration can be exported by several entry points;
        // links go to the first in package.json order.
        if (scope === 'javascript') continue;
        throw new Error(
          `${symbol} is documented on both ${index.get(symbol)!.route} and ${page.route}`,
        );
      }
      index.set(symbol, {route: page.route, anchor});
    }
  }
  return index;
}

/** Every generated reference page, keyed by its file. */
export async function referenceOutputs(
  root = ROOT,
): Promise<ReadonlyMap<string, string>> {
  const libraries = teaLibraries();
  const pages = [
    ...builtinPages(libraries),
    ...libraryPages(libraries),
    cliPage(),
    ...javascriptPages(),
  ];
  const indexes = {
    tea: symbolIndex(pages, 'tea'),
    javascript: symbolIndex(pages, 'javascript'),
  };
  return new Map([
    [
      path.join(root, 'docs/assets/tea.tmLanguage.json'),
      JSON.stringify({...generateGrammar(), name: 'tea', displayName: 'Tea'}),
    ],
    [
      path.join(root, 'docs/reference/overview.md'),
      await overviewPage(root, pages),
    ],
    ...pages.map(
      page =>
        [
          path.join(root, 'docs', `${page.route}.md`),
          renderPage(page, indexes[page.scope]),
        ] as const,
    ),
  ]);
}

/**
 * Turn site routes (`/requests`, `/reference/builtins/ta#tasma`) into links to
 * real sibling files, so the Markdown reads the same on the web and inside an
 * extracted package. A route without a page is an error.
 */
function portableLinks(content: string, file: string, root: string): string {
  return content.replace(
    /\]\(\/([^)#\s]*)(#[^)\s]*)?\)/g,
    (_, route: string, anchor = '') => {
      const target = path.join(root, 'docs', `${route.replace(/\/$/, '')}.md`);
      if (!existsSync(target) && !route.startsWith('reference/')) {
        throw new Error(
          `${path.relative(root, file)} links to missing page /${route}`,
        );
      }
      const relative = path
        .relative(path.dirname(file), target)
        .split(path.sep)
        .join('/');
      return `](${relative.startsWith('.') ? relative : `./${relative}`}${anchor})`;
    },
  );
}

async function generatedFiles(directory: string): Promise<string[]> {
  const found: string[] = [];
  for (const item of await readdir(directory, {withFileTypes: true})) {
    const file = path.join(directory, item.name);
    if (item.isDirectory()) found.push(...(await generatedFiles(file)));
    else if (
      item.name.endsWith('.md') &&
      (await readFile(file, 'utf8')).includes(GENERATED)
    ) {
      found.push(file);
    }
  }
  return found;
}

interface GenerateOptions {
  readonly root?: string;
  readonly check?: boolean;
  readonly report?: (message: string) => void;
}

/** Write the reference, or with `check` report every file that would change. */
export async function generateReference(
  options: GenerateOptions = {},
): Promise<boolean> {
  const root = options.root ?? ROOT;
  const check = options.check ?? false;
  const report = options.report ?? (message => console.error(message));
  let stale = false;
  const outputs = await referenceOutputs(root);
  for (const [file, content] of outputs) {
    const formatted = await format(
      path.extname(file) === '.json'
        ? content
        : portableLinks(content, file, root),
      {parser: path.extname(file) === '.json' ? 'json' : 'mdx'},
    );
    const current = existsSync(file) ? await readFile(file, 'utf8') : undefined;
    if (current === formatted) continue;
    if (check) {
      stale = true;
      report(`Generated reference is stale: ${path.relative(root, file)}`);
      continue;
    }
    await mkdir(path.dirname(file), {recursive: true});
    await writeFile(file, formatted, 'utf8');
  }
  for (const file of await generatedFiles(path.join(root, 'docs/reference'))) {
    if (outputs.has(file)) continue;
    if (check) {
      stale = true;
      report(
        `Generated reference page has no source: ${path.relative(root, file)}`,
      );
      continue;
    }
    await rm(file);
    // Drop directories the removed page leaves empty, up to docs/reference.
    for (
      let directory = path.dirname(file);
      directory !== path.join(root, 'docs/reference') &&
      (await readdir(directory)).length === 0;
      directory = path.dirname(directory)
    ) {
      await rm(directory, {recursive: true});
    }
  }
  if (!stale && check) console.log('Generated Tea reference is current.');
  return !stale;
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === SCRIPT_FILE
) {
  const current = await generateReference({
    check: process.argv.includes('--check'),
  });
  if (!current) process.exitCode = 1;
}
