// Purpose: Render the Tea reference from the code that owns each surface — native catalog docs, `/** */` library docs, TSDoc, and the CLI command tree.

import {existsSync} from 'node:fs';
import {mkdir, readFile, readdir, rm, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {format} from 'prettier';
import {generateGrammar} from '../../editors/vscode/scripts/generate-syntax';
import {
  CATALOG,
  formatNativeSignature,
  formatNativeTypeRef,
  type NativeFunc,
  type NativeVar,
} from '../../src/checker/catalog';
import {
  NATIVE_FUNCTION_DOCS,
  NATIVE_VALUE_DOCS,
} from '../../src/checker/catalog-docs';
import {cliProgram} from '../../src/cli/cli';
import {analyze} from '../../src/lsp/analysis';
import {hover} from '../../src/lsp/name-queries';
import {
  docSections,
  nativeFunctionDocs,
  nativeValueDocs,
  wrapSignature,
} from '../../src/lsp/documentation';
import type {
  ReferenceEntry,
  ReferenceManual,
  ReferencePage,
  ReferenceParameter,
} from '../../src/reference/index';
import type {DocComment, DocExample} from '../../src/syntax/doc-comments';
import {formatType, Qualifier, TypeKind} from '../../src/ir/type';
import {AssignOp} from '../../src/syntax/nodes';
import {KEYWORDS, Op} from '../../src/syntax/tokens';
import {
  javascriptApi,
  type ApiDoc,
  type ApiExport,
  type ApiKind,
} from './javascript-api-docs';
import {exampleKey, runExamples} from './run-examples';
import {
  qualifiedName,
  teaLibraries,
  type LibraryExport,
  type LibraryParam,
  type TeaLibrary,
} from './tea-library-docs';

const SCRIPT_FILE = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(SCRIPT_FILE), '../..');
const GENERATED =
  '{/* Generated by scripts/docs/generate-reference.ts. Do not edit by hand. */}';

/** What each of a doc comment's examples writes, in example order. */
type Outputs = (doc: DocComment) => string[];

// ---- page model -------------------------------------------------------------

interface ParamRow {
  readonly name: string;
  readonly type: string | null;
  readonly defaultValue: string | null;
  readonly description: string;
}

/** What an entry documents, for readers that label or format it by kind. */
type EntryKind =
  | 'function'
  | 'variable'
  | 'constant'
  | 'type'
  | 'enum'
  | 'interface'
  | 'class'
  | 'command';

interface Entry {
  /** As code writes it: `ta.sma`, `trade.NextOpenTrade`, `tea run`. */
  readonly name: string;
  readonly kind: EntryKind;
  /**
   * The page heading. Mintlify and Docusaurus slug punctuation differently
   * (`ta.sma` becomes `ta-sma` in one and `tasma` in the other) and neither
   * reads explicit ids from both, so headings hold only letters, digits, `_`
   * and spaces: the name within its page's namespace, `sma` on the `ta` page.
   * Empty for a table that sits directly under its category heading.
   */
  readonly heading: string;
  /** Names a `{@link …}` resolves to this entry. */
  readonly symbols: readonly string[];
  readonly summary: string;
  /** One per overload; a long one may span lines. */
  readonly signatures: readonly string[];
  readonly params: readonly ParamRow[];
  readonly returns: string | null;
  /** One table row per member: its declaration, value or name, then notes. */
  readonly table: {
    readonly columns: readonly string[];
    readonly rows: readonly (readonly string[])[];
  } | null;
  readonly body: string;
  /** Methods, each with its own heading under its owner. */
  readonly members: readonly Entry[];
  /** A difference from Pine Script v6, listed on the compatibility page. */
  readonly pine: string | null;
  readonly category: string;
}

interface Page {
  readonly route: string;
  readonly title: string;
  readonly description: string;
  readonly intro: string;
  readonly language: 'tea' | 'ts' | 'bash';
  readonly scope: 'tea' | 'javascript';
  /** What the parameter table calls its rows: `Parameter` or `Argument`. */
  readonly paramLabel: string;
  readonly entries: readonly Entry[];
  /** Parameters documented once for the page instead of on every entry. */
  readonly shared: readonly ParamRow[];
  /**
   * Each entry has its own page at `<route>/<heading>`, and this page lists
   * them by category.
   */
  readonly perEntry: boolean;
}

function entry(
  fields: Partial<Entry> &
    Pick<Entry, 'name' | 'kind' | 'summary' | 'category'>,
): Entry {
  return {
    heading: fields.name.slice(fields.name.lastIndexOf('.') + 1),
    symbols: [fields.name],
    signatures: [],
    params: [],
    returns: null,
    table: null,
    body: '',
    members: [],
    pine: null,
    ...fields,
  };
}

// ---- built-in pages ---------------------------------------------------------

interface BuiltinPage {
  readonly slug: string;
  readonly title: string;
  readonly description: string;
  readonly intro: string;
  readonly natives: (name: string) => boolean;
  /** A library whose exports the page holds: all, or those of some categories. */
  readonly library?: string;
  readonly categories?: (category: string) => boolean;
  readonly shared?: readonly string[];
  readonly perEntry?: boolean;
}

const namespace =
  (...names: string[]) =>
  (name: string) =>
    names.some(prefix => name.startsWith(`${prefix}.`));

const METHOD_FORM =
  'Every function whose first parameter is `self` can also be called as a method on the collection: `values.push(x)` is the same call as `array.push(values, x)`.';

const COLLECTION_COPIES =
  'Unlike Pine Script, where collections are references, a Tea collection is a value: assigning it or passing it to a function copies it, so a function that pushes to its argument leaves the caller’s collection unchanged.';

const BUILTIN_PAGES: readonly BuiltinPage[] = [
  {
    slug: 'price-and-volume',
    title: 'Price and volume',
    description:
      'The current bar’s open, high, low, close and volume, and the averages built from them.',
    intro: '',
    library: 'pine',
    natives: () => false,
  },
  {
    slug: 'bar-and-time',
    title: 'Bar and time',
    description:
      'The bar number, the bar’s time, the clock, and where the bar stands in the data.',
    intro:
      'Values the host supplies for the current bar, available in every script without an import.',
    natives: name =>
      ['bar_index', 'time', 'timenow'].includes(name) ||
      namespace('barstate')(name),
  },
  {
    slug: 'symbol-and-timeframe',
    title: 'Symbol and timeframe',
    description:
      'The symbol and the timeframe a host binds the script to, such as `NASDAQ:AAPL` and `D`.',
    intro:
      'Values the host supplies when it binds the script, available in every script without an import. `tea run` supplies none of them, so there they are `na`, or `false` for the `timeframe.is*` flags.',
    natives: namespace('syminfo', 'timeframe'),
  },
  {
    slug: 'input',
    title: 'input',
    description: 'Script inputs a host can set without editing the source.',
    intro:
      'An input declares a value the host supplies when it binds the script, falling back to the default written in the source. {@link input} explains how inputs are named and when their values are fixed.',
    natives: name => name === 'input' || name.startsWith('input.'),
    shared: [
      'title',
      'tooltip',
      'inline',
      'group',
      'confirm',
      'display',
      'active',
    ],
  },
  {
    slug: 'request',
    title: 'request',
    description: 'Calculations evaluated in another symbol or timeframe.',
    intro:
      'A request evaluates an expression in a child context fed by its own data stream. [Request synchronization](/requests) explains binding and synchronization in depth.',
    natives: namespace('request'),
  },
  {
    slug: 'plots',
    title: 'Plots',
    description:
      'Lines, levels, fills, shapes, characters and colors a host draws, and their style constants.',
    intro:
      'Each call writes one named output that a host can draw. See [outputs and events](/language-guide/outputs-and-events).',
    library: 'visual',
    categories: category => category !== 'Alerts',
    natives: namespace(
      'plot',
      'hline',
      'location',
      'shape',
      'size',
      'display',
      'format',
      'position',
    ),
  },
  {
    slug: 'alerts',
    title: 'Alerts',
    description: 'Alert conditions and alert messages a host can deliver.',
    intro:
      'Each call writes one named output that a host can deliver as an alert. See [outputs and events](/language-guide/outputs-and-events).',
    library: 'visual',
    categories: category => category === 'Alerts',
    natives: () => false,
  },
  {
    slug: 'ta',
    title: 'ta',
    description:
      'Moving averages, oscillators, bands, crosses, pivots and volume indicators.',
    intro: '',
    library: 'ta',
    natives: () => false,
    perEntry: true,
  },
  {
    slug: 'core',
    title: 'Core functions',
    description:
      'Missing values, conversions, script declarations and script errors.',
    intro: 'Functions available in every script without an import.',
    natives: name =>
      [
        'na',
        'nz',
        'int',
        'float',
        'str.tostring',
        'runtime.error',
        'indicator',
        'library',
      ].includes(name),
  },
  {
    slug: 'math',
    title: 'math',
    description: 'Arithmetic helpers and mathematical constants.',
    intro: 'Functions and constants in the `math` namespace.',
    natives: namespace('math'),
  },
  {
    slug: 'color',
    title: 'color',
    description: 'Color construction and Tea’s standard palette.',
    intro: 'Functions and constants in the `color` namespace.',
    natives: namespace('color'),
  },
  {
    slug: 'array',
    title: 'array',
    description: 'Functions for ordered, variable-length collections.',
    intro: `See [types](/reference/language/types) for the \`array<T>\` type and [memory model](/memory-model) for how array values are copied and shared. ${COLLECTION_COPIES} ${METHOD_FORM}`,
    natives: namespace('array'),
  },
  {
    slug: 'matrix',
    title: 'matrix',
    description: 'Functions for two-dimensional collections.',
    intro: `See [types](/reference/language/types) for the \`matrix<T>\` type and [memory model](/memory-model) for how matrix values are copied and shared. ${COLLECTION_COPIES} ${METHOD_FORM}`,
    natives: namespace('matrix'),
  },
  {
    slug: 'map',
    title: 'map',
    description: 'Functions for key-value collections.',
    intro: `See [types](/reference/language/types) for the \`map<K, V>\` type and [memory model](/memory-model) for how map values are copied and shared. ${COLLECTION_COPIES} ${METHOD_FORM}`,
    natives: namespace('map'),
  },
];

/** Libraries a script imports; these keep one page per entry. */
const PER_ENTRY_LIBRARIES = ['trade', 'broker', 'portfolio'];

const isLiteral = (value: NativeVar) =>
  value.qualifier === Qualifier.Const && !value.name.includes('.');

function qualifierType(qualifier: string, type: string): string {
  return `${qualifier} ${type}`;
}

/**
 * Facts the catalog states about a parameter, as reader-facing notes. A note
 * appears only when every overload agrees: `input(close)` takes a series even
 * though the other `input` overloads need a constant `defval`.
 */
function parameterNotes(
  overloads: readonly NativeFunc[],
  name: string,
): string {
  const params = overloads.flatMap(overload =>
    overload.params.filter(param => param.name === name),
  );
  const notes: string[] = [];
  if (params.every(param => param.constLiteral)) {
    notes.push('Must be a compile-time constant.');
  }
  if (
    params.every(param => !param.acceptsNa) &&
    params.every(
      param =>
        typeof param.type === 'string' || param.type.kind !== TypeKind.Bool,
    )
  ) {
    notes.push('Cannot be `na`.');
  }
  if (params.every(param => param.mode === 'inout')) {
    notes.push('Must be a variable or field; the call updates it.');
  }
  if (params.every(param => param.capture)) {
    notes.push('Evaluated in the requested context.');
  }
  return notes.join(' ');
}

function nativeParams(
  name: string,
  overloads: readonly NativeFunc[],
): ParamRow[] {
  const doc = NATIVE_FUNCTION_DOCS[name]!;
  const order: string[] = [];
  const types = new Map<string, Set<string>>();
  for (const overload of overloads) {
    for (const param of overload.params) {
      if (param.availability !== 'supported') continue;
      if (!types.has(param.name)) {
        order.push(param.name);
        types.set(param.name, new Set());
      }
      types
        .get(param.name)!
        .add(
          qualifierType(param.qualifierCap, formatNativeTypeRef(param.type)),
        );
    }
  }
  return order.map(param => {
    const prose = doc.params[param];
    if (prose === undefined) {
      throw new Error(
        `native function ${name} does not document parameter ${param}`,
      );
    }
    const notes = parameterNotes(overloads, param);
    return {
      name: param,
      type: [...types.get(param)!].join(', '),
      defaultValue: null,
      description: notes === '' ? prose : `${prose} ${notes}`,
    };
  });
}

function nativeFunctionEntry(
  name: string,
  overloads: readonly NativeFunc[],
  outputs: Outputs,
): Entry {
  const doc = nativeFunctionDocs(name);
  if (doc === null)
    throw new Error(`native function ${name} has no documentation`);
  return entry({
    name,
    kind: 'function',
    summary: doc.summary,
    signatures: overloads.map(formatNativeSignature),
    params: nativeParams(name, overloads),
    returns: doc.returns,
    body: docSections(doc, outputs(doc)),
    pine: doc.pine,
    category: doc.category!,
  });
}

function valueSignature(value: NativeVar): string {
  const declared = `${value.qualifier} ${formatType(value.type)} ${value.name}`;
  return value.qualifier === Qualifier.Const
    ? `${declared} = ${formatConstant(value)}`
    : declared;
}

function formatConstant(value: NativeVar): string {
  if (typeof value.value === 'string' && value.type.kind === TypeKind.String) {
    return JSON.stringify(value.value);
  }
  return String(value.value);
}

function valueEntries(values: readonly NativeVar[], outputs: Outputs): Entry[] {
  const entries: Entry[] = [];
  const families = new Set<string>();
  for (const value of values) {
    const key = Object.keys(NATIVE_VALUE_DOCS).find(candidate =>
      candidate.endsWith('*')
        ? value.name.startsWith(candidate.slice(0, -1))
        : candidate === value.name,
    );
    if (key === undefined)
      throw new Error(`native value ${value.name} has no documentation`);
    const members = NATIVE_VALUE_DOCS[key]!.members;
    const doc = nativeValueDocs(key)!;
    if (!key.endsWith('*')) {
      entries.push(
        entry({
          name: value.name,
          kind: value.qualifier === Qualifier.Const ? 'constant' : 'variable',
          summary: doc.summary,
          signatures: [valueSignature(value)],
          body: docSections(doc, outputs(doc)),
          pine: doc.pine,
          category: doc.category!,
        }),
      );
      continue;
    }
    if (families.has(key)) continue;
    families.add(key);
    const family = values.filter(member =>
      member.name.startsWith(key.slice(0, -1)),
    );
    const notes = family.some(member => members?.[member.name] !== undefined);
    entries.push(
      entry({
        name: key,
        kind: 'constant',
        // `plot.style_*` reads "plot style"; `color.*` reads "color".
        heading: key.replace(/[*._]+$/, '').replaceAll('.', ' '),
        symbols: family.map(member => member.name),
        summary: doc.summary,
        table: {
          columns: notes
            ? ['Constant', 'Value', 'Description']
            : ['Constant', 'Value'],
          rows: family.map(member => [
            code(member.name),
            code(formatConstant(member)),
            ...(notes ? [members?.[member.name] ?? ''] : []),
          ]),
        },
        body: joinBlocks(
          `Each constant is a ${code(`const ${formatType(family[0]!.type)}`)}.`,
          docSections(doc, outputs(doc)),
        ),
        pine: doc.pine,
        category: doc.category!,
      }),
    );
  }
  return entries;
}

function builtinPages(
  libraries: readonly TeaLibrary[],
  outputs: Outputs,
): Page[] {
  const values = [...CATALOG.vars.values()].filter(value => !isLiteral(value));
  const placed = new Map<string, string>();
  const place = (name: string, slug: string) => {
    const previous = placed.get(name);
    if (previous !== undefined) {
      throw new Error(`${name} belongs to both ${previous} and ${slug} pages`);
    }
    placed.set(name, slug);
  };
  const pages = BUILTIN_PAGES.map(config => {
    const library =
      config.library === undefined
        ? undefined
        : libraries.find(candidate => candidate.name === config.library)!;
    const functions = [...CATALOG.funcs].filter(([name]) =>
      config.natives(name),
    );
    const pageValues = values.filter(value => config.natives(value.name));
    for (const [name] of functions) place(name, config.slug);
    for (const value of pageValues) place(value.name, config.slug);
    const exported =
      library === undefined
        ? []
        : libraryEntries(library, outputs).filter(
            item => config.categories?.(item.category) ?? true,
          );
    for (const item of exported) place(item.name, config.slug);
    const entries = [
      ...exported,
      ...functions.map(([name, overloads]) =>
        nativeFunctionEntry(name, overloads, outputs),
      ),
      ...valueEntries(pageValues, outputs),
    ];
    return finishShared(
      {
        route: `reference/builtins/${config.slug}`,
        title: config.title,
        description: config.description,
        intro: joinBlocks(
          config.intro,
          library === undefined ? undefined : libraryIntro(library, outputs),
        ),
        language: 'tea',
        scope: 'tea',
        paramLabel: 'Parameter',
        entries,
        shared: [],
        perEntry: config.perEntry ?? false,
      },
      config.shared ?? [],
    );
  });
  const unplaced = [
    ...[...CATALOG.funcs.keys()],
    ...values.map(value => value.name),
    ...libraries
      .filter(library => library.access !== 'import')
      .flatMap(library =>
        library.exports.map(item => qualifiedName(library, item.name)),
      ),
  ].filter(name => !placed.has(name));
  if (unplaced.length > 0) {
    throw new Error(`no reference page holds: ${unplaced.join(', ')}`);
  }
  return pages;
}

/** Move parameters documented identically on every entry into one table. */
function finishShared(page: Page, names: readonly string[]): Page {
  if (names.length === 0) return page;
  const shared = new Map<string, ParamRow>();
  const entries = page.entries.map(item => {
    const own = item.params.filter(param => !names.includes(param.name));
    const common = item.params.filter(param => names.includes(param.name));
    for (const param of common) {
      const previous = shared.get(param.name);
      if (
        previous !== undefined &&
        previous.description !== param.description
      ) {
        throw new Error(
          `${page.title}: parameter ${param.name} must read the same on every entry (${item.name})`,
        );
      }
      if (previous !== undefined && previous.type !== param.type) {
        shared.set(param.name, {
          ...previous,
          type: `${previous.type}, ${param.type}`,
        });
      } else if (previous === undefined) {
        shared.set(param.name, param);
      }
    }
    const also =
      common.length === 0
        ? ''
        : `Also accepts the [common parameters](#common-parameters) ${common.map(param => code(param.name)).join(', ')}.`;
    return {...item, params: own, body: joinBlocks(also, item.body)};
  });
  return {
    ...page,
    entries,
    shared: names.flatMap(name =>
      shared.has(name) ? [shared.get(name)!] : [],
    ),
  };
}

// ---- library pages ----------------------------------------------------------

function libraryIntro(library: TeaLibrary, outputs: Outputs): string {
  if (library.doc === null)
    throw new Error(`${library.file}: library() has no doc comment`);
  const access =
    library.access === 'global'
      ? 'Available in every script without an import or namespace.'
      : library.access === 'namespace'
        ? `Available in every script as ${code(`${library.name}.name`)} without an import.`
        : `Add ${code(`import ${library.name}`)} to a script to use these as ${code(`${library.name}.name`)}.`;
  return joinBlocks(
    library.doc.summary,
    docSections(library.doc, outputs(library.doc)),
    access,
  );
}

function memberText(doc: DocComment | null, where: string): string {
  if (doc === null) throw new Error(`${where} has no doc comment`);
  if (docSections({...doc, body: ''}) !== '' || doc.body.includes('```')) {
    throw new Error(
      `${where}: field and enum member docs render in a table and cannot hold examples or other sections`,
    );
  }
  return [doc.summary, doc.body].filter(part => part !== '').join(' ');
}

/**
 * Library text as a script writes it: the library's own types, enums and
 * interfaces, which its source names bare, gain its namespace, so
 * `Commission.new(CommissionKind.rate, 0.0)` reads
 * `broker.Commission.new(broker.CommissionKind.rate, 0.0)`. Strings stay.
 */
function qualify(library: TeaLibrary, text: string): string {
  if (library.access === 'global') return text;
  const types = new Set(
    library.exports
      .filter(item => item.kind !== 'function' && item.kind !== 'value')
      .map(item => item.name),
  );
  return text
    .split(/("(?:[^"\\]|\\.)*")/)
    .map((part, index) =>
      index % 2 === 1
        ? part
        : part.replace(/(?<![.\w])[A-Za-z_]\w*/g, word =>
            types.has(word) ? `${library.name}.${word}` : word,
          ),
    )
    .join('');
}

function libraryParams(
  library: TeaLibrary,
  params: readonly LibraryParam[],
  doc: DocComment,
  where: string,
): ParamRow[] {
  return params.map(param => {
    const description = doc.params.get(param.name);
    if (description === undefined) {
      throw new Error(`${where} does not document parameter ${param.name}`);
    }
    return {
      name: param.name,
      type: param.type === null ? null : qualify(library, param.type),
      defaultValue:
        param.defaultValue === null
          ? null
          : qualify(library, param.defaultValue),
      description,
    };
  });
}

function librarySignature(library: TeaLibrary, item: LibraryExport): string {
  if (item.kind === 'value') {
    // A value's type is the checker's: what an editor shows for it.
    const source = `x = ${qualifiedName(library, item.name)}`;
    const shown = hover(analyze({filename: 'value.tea', source}), {
      line: 0,
      character: source.length - 1,
    });
    const line = /^```tea\n(.+) \w+\n/.exec(
      (shown?.contents as {value: string} | undefined)?.value ?? '',
    );
    if (line === null)
      throw new Error(`${library.file}: no type for ${item.name}`);
    return `${line[1]} ${qualifiedName(library, item.name)}`;
  }
  if (item.kind !== 'function') return item.declaration;
  const params = item.params.map(param =>
    qualify(
      library,
      `${param.type === null ? '' : `${param.type} `}${param.name}${param.defaultValue === null ? '' : ` = ${param.defaultValue}`}`,
    ),
  );
  return `${qualifiedName(library, item.name)}(${params.join(', ')})`;
}

// Readers start from what they call, then read the types those calls use.
const READING_ORDER: Readonly<Record<LibraryExport['kind'], number>> = {
  function: 0,
  value: 0,
  type: 1,
  enum: 1,
  interface: 1,
};

function libraryEntries(library: TeaLibrary, outputs: Outputs): Entry[] {
  const exports = [...library.exports].sort(
    (a, b) => READING_ORDER[a.kind] - READING_ORDER[b.kind],
  );
  return exports.map(item => {
    const where = `${library.file}:${item.line} ${item.name}`;
    const doc = item.doc;
    if (doc === null) throw new Error(`${where} has no doc comment`);
    const name = qualifiedName(library, item.name);
    const category = doc.category ?? 'Declarations';
    const listed = item.members.filter(member => member.kind !== 'method');
    return entry({
      name,
      kind: item.kind === 'value' ? 'variable' : item.kind,
      heading: item.name,
      summary: doc.summary,
      signatures: [librarySignature(library, item)],
      params: libraryParams(library, item.params, doc, where),
      returns: doc.returns,
      table:
        listed.length === 0
          ? null
          : {
              columns: [
                item.kind === 'enum' ? 'Member' : 'Field',
                'Description',
              ],
              rows: listed.map(member => [
                code(qualify(library, member.declaration)),
                memberText(
                  member.doc,
                  `${library.file}:${member.line} ${item.name}.${member.name}`,
                ),
              ]),
            },
      body: docSections(doc, outputs(doc)),
      pine: doc.pine,
      members: item.members
        .filter(member => member.kind === 'method')
        .map(member => {
          const at = `${library.file}:${member.line} ${item.name}.${member.name}`;
          if (member.doc === null) throw new Error(`${at} has no doc comment`);
          return entry({
            name: `${name}.${member.name}`,
            kind: 'function',
            heading: member.name,
            summary: member.doc.summary,
            signatures: [qualify(library, member.declaration)],
            params: libraryParams(library, member.params, member.doc, at),
            returns: member.doc.returns,
            body: docSections(member.doc, outputs(member.doc)),
            pine: member.doc.pine,
            category,
          });
        }),
      category,
    });
  });
}

function libraryPages(
  libraries: readonly TeaLibrary[],
  outputs: Outputs,
): Page[] {
  return libraries
    .filter(library => library.access === 'import')
    .map(library => ({
      route: `reference/libraries/${library.name}`,
      title: library.name,
      description: library.doc?.summary ?? '',
      intro: libraryIntro(library, outputs),
      language: 'tea',
      scope: 'tea',
      paramLabel: 'Parameter',
      entries: libraryEntries(library, outputs),
      shared: [],
      perEntry: PER_ENTRY_LIBRARIES.includes(library.name),
    }));
}

// ---- JavaScript API pages ---------------------------------------------------

const API_CATEGORIES: Readonly<Record<ApiKind, string>> = {
  function: 'Functions',
  class: 'Classes',
  interface: 'Interfaces',
  type: 'Types',
  enum: 'Enums',
  constant: 'Constants',
};

function splitSummary(text: string): {summary: string; rest: string} {
  const [summary = '', ...rest] = text.trim().split(/\n\s*\n/);
  return {summary: summary.replace(/\s*\n\s*/g, ' '), rest: rest.join('\n\n')};
}

function firstSentence(text: string): string {
  return /^.+?[.!?](?=\s|$)/.exec(text)?.[0] ?? text;
}

/**
 * TSDoc examples are Markdown: fenced code stays as written, a sentence with
 * inline code reads as prose, and bare code gets a fence.
 */
function apiExamples(doc: ApiDoc): string {
  return doc.examples
    .map(example =>
      example.includes('```')
        ? example
        : example.includes('`')
          ? `**Example:** ${example}`
          : fence(example, 'ts')!,
    )
    .join('\n\n');
}

function apiEntry(item: ApiExport, heading: string): Entry {
  const {summary, rest} = splitSummary(item.doc.text);
  return entry({
    name: item.name,
    kind: item.kind,
    heading,
    summary,
    signatures: [item.signature],
    params: apiParams(item.doc),
    returns: item.doc.returns,
    body: joinBlocks(
      item.typeOnly
        ? 'A type-only export: it names a type, and no value of that name exists at run time, so `new` and `instanceof` cannot use it.'
        : undefined,
      rest,
      apiExamples(item.doc),
    ),
    members: item.members.map(member => {
      const text = splitSummary(member.doc.text);
      return entry({
        name: `${item.name}.${member.name}`,
        kind: 'function',
        heading: `${heading} ${member.name}`,
        summary: text.summary,
        signatures: [member.signature],
        params: apiParams(member.doc),
        returns: member.doc.returns,
        body: joinBlocks(text.rest, apiExamples(member.doc)),
        category: API_CATEGORIES[item.kind],
      });
    }),
    category: API_CATEGORIES[item.kind],
  });
}

function apiParams(doc: ApiDoc): ParamRow[] {
  return [...doc.params].map(([name, text]) => ({
    name,
    type: null,
    defaultValue: null,
    description: text,
  }));
}

function javascriptPages(): Page[] {
  return javascriptApi().map(api => {
    const order = Object.keys(API_CATEGORIES);
    const exports = [...api.exports].sort(
      (a, b) =>
        order.indexOf(a.kind) - order.indexOf(b.kind) ||
        a.name.localeCompare(b.name),
    );
    const headed = exports.filter(item => !isTableConstant(item));
    // Headings slug case-insensitively, but `Color` and `color` are two
    // exports: such names carry their kind, "Color class" and "color function".
    const folded = headed.map(item => item.name.toLowerCase());
    const description = splitSummary(api.description ?? '');
    return {
      route: `reference/javascript/${api.specifier === 'tea' ? 'tea' : api.specifier.slice(4).replaceAll('/', '-')}`,
      title: api.specifier,
      description: firstSentence(description.summary),
      intro: joinBlocks(
        `\`\`\`ts\nimport {…} from '${api.specifier}';\n\`\`\``,
        description.summary,
        description.rest,
      ),
      language: 'ts',
      scope: 'javascript',
      paramLabel: 'Parameter',
      shared: [],
      perEntry: false,
      entries: [
        ...headed.map(item =>
          apiEntry(
            item,
            folded.filter(name => name === item.name.toLowerCase()).length > 1
              ? `${item.name} ${item.kind}`
              : item.name,
          ),
        ),
        ...constantTable(exports),
      ],
    };
  });
}

/** A constant whose whole story is one declaration line and a sentence or two. */
function isTableConstant(item: ApiExport): boolean {
  return (
    item.kind === 'constant' &&
    !item.signature.includes('\n') &&
    item.doc.examples.length === 0
  );
}

/** One-line constants, such as the clock units `ms` and `M`, read best as one table. */
function constantTable(exports: readonly ApiExport[]): Entry[] {
  const constants = exports.filter(isTableConstant);
  if (constants.length === 0) return [];
  return [
    entry({
      name: 'Constants',
      kind: 'constant',
      heading: '',
      symbols: constants.map(item => item.name),
      summary: '',
      table: {
        columns: ['Constant', 'Declaration', 'Description'],
        rows: constants.map(item => [
          code(item.name),
          code(item.signature.replace(/;$/, '')),
          item.doc.text,
        ]),
      },
      category: API_CATEGORIES.constant,
    }),
  ];
}

// ---- CLI page ---------------------------------------------------------------

/** Flags in help text as code, which Mintlify would otherwise turn into dashes. */
// Options, `input@line:col` names and wildcard names such as `request.*`
// read as code, which also keeps Markdown from taking `*` for emphasis.
function flags(text: string): string {
  return text.replace(
    /(?<![`\w-])(--?[A-Za-z][\w-]*(?:=\w+)?|input@\d+:\d+|[a-z]+\.[a-z_]*\*)/g,
    '`$1`',
  );
}

function cliPage(): Page {
  const program = cliProgram(() => {});
  const entries = program.commands.map(command => {
    const usage = `tea ${command.name()} ${command.usage()}`.trim();
    const args = command.registeredArguments.map(argument => ({
      name: argument.name(),
      type: null,
      defaultValue: null,
      description: `${sentence(argument.description)}${argument.required ? '' : ' Optional.'}`,
    }));
    const options = command.options.map(option => {
      const fallback =
        option.negate || option.defaultValue === undefined
          ? ''
          : ` Default: ${option.defaultValueDescription ?? code(String(option.defaultValue))}.`;
      return [
        code(option.flags),
        `${sentence(option.description)}${fallback}${option.mandatory ? ' Required.' : ''}`,
      ];
    });
    const summary = flags(
      punctuate(command.summary() || command.description()),
    );
    const description = flags(punctuate(command.description()));
    return entry({
      name: `tea ${command.name()}`,
      kind: 'command',
      heading: `tea ${command.name()}`,
      summary,
      body: description === summary ? '' : description,
      signatures: [usage],
      params: args,
      table:
        options.length === 0
          ? null
          : {columns: ['Option', 'Description'], rows: options},
      category: 'Commands',
    });
  });
  return {
    route: 'reference/tools/cli',
    title: 'tea command',
    description: punctuate(program.description()),
    intro:
      'The `tea` command compiles, runs and inspects Tea scripts, serves this documentation offline, and runs the language server. Every command accepts `--help`; `tea --version` prints the version. Set the `TEA_LOG` environment variable to `debug`, `info`, `warn` or `error` to change how much the command logs.',
    language: 'bash',
    scope: 'tea',
    paramLabel: 'Argument',
    entries,
    shared: [],
    perEntry: false,
  };
}

// ---- rendering --------------------------------------------------------------

function code(value: string): string {
  const ticks = value.includes('`') ? '``' : '`';
  return `${ticks}${value}${ticks}`;
}

function fence(
  source: string | undefined,
  language = 'tea',
): string | undefined {
  return source === undefined
    ? undefined
    : `\`\`\`${language}\n${source}\n\`\`\``;
}

function joinBlocks(...blocks: readonly (string | undefined)[]): string {
  return blocks
    .filter(block => block !== undefined && block.trim() !== '')
    .join('\n\n');
}

function punctuate(text: string): string {
  return /[.!?]$/.test(text) ? text : `${text}.`;
}

/** Commander help reads `port to bind`; reference tables read sentences. */
function sentence(text: string): string {
  return punctuate(text.charAt(0).toUpperCase() + text.slice(1));
}

/** The slug both renderers give a heading of letters, digits, `_` and spaces. */
function slug(heading: string): string {
  if (!/^[A-Za-z0-9_ ]+$/.test(heading)) {
    throw new Error(
      `heading '${heading}' must hold only letters, digits, _ and spaces`,
    );
  }
  return heading.toLowerCase().replaceAll(' ', '-');
}

function categories(page: Page): Map<string, Entry[]> {
  const grouped = new Map<string, Entry[]>();
  for (const item of page.entries) {
    const list = grouped.get(item.category) ?? [];
    list.push(item);
    grouped.set(item.category, list);
  }
  return grouped;
}

interface Target {
  readonly route: string;
  /** Empty for an entry with its own page. */
  readonly anchor: string;
}

/** Hands out heading slugs for one file, failing on a repeat. */
function headingSlugs(route: string): (heading: string) => string {
  const slugs = new Set<string>();
  return heading => {
    const id = slug(heading);
    // The renderers number repeated headings differently.
    if (slugs.has(id))
      throw new Error(`${route}: two headings read '${heading}'`);
    slugs.add(id);
    return id;
  };
}

/** A member's heading where it shares its page with other entries. */
function memberHeading(page: Page, owner: Entry, member: Entry): string {
  return page.perEntry ? member.heading : `${owner.heading} ${member.heading}`;
}

/**
 * Where each symbol of a page is documented: a heading on a page that lists
 * entries, or, on a per-entry page, the entry's own page, whose methods are
 * headings.
 */
function targets(page: Page): Map<string, Target> {
  const found = new Map<string, Target>();
  if (page.perEntry) {
    const files = new Set<string>();
    for (const item of page.entries) {
      // Entry pages are files: names that differ only in case would collide.
      if (
        !/^\w+$/.test(item.heading) ||
        files.has(item.heading.toLowerCase())
      ) {
        throw new Error(
          `${page.route}: '${item.heading}' cannot name its own page`,
        );
      }
      files.add(item.heading.toLowerCase());
      const route = `${page.route}/${item.heading}`;
      for (const symbol of item.symbols) found.set(symbol, {route, anchor: ''});
      const claim = headingSlugs(route);
      if (item.members.length > 0) claim('Methods');
      for (const member of item.members) {
        found.set(member.name, {route, anchor: claim(member.heading)});
      }
    }
    return found;
  }
  const claim = headingSlugs(page.route);
  if (page.shared.length > 0) claim('Common parameters');
  for (const [category, items] of categories(page)) {
    const categoryId = claim(category.replace(/[^A-Za-z0-9_ ]/g, ''));
    for (const item of items) {
      const id = item.heading === '' ? categoryId : claim(item.heading);
      for (const symbol of item.symbols) {
        found.set(symbol, {route: page.route, anchor: id});
      }
      for (const member of item.members) {
        found.set(member.name, {
          route: page.route,
          anchor: claim(memberHeading(page, item, member)),
        });
      }
    }
  }
  return found;
}

type SymbolIndex = ReadonlyMap<string, Target>;

/** What prose needs to know about the file it is written into. */
interface Place {
  readonly route: string;
  readonly scope: Page['scope'];
}

const LINK = /\{@link\s+([^\s}|]+)(?:\s*\|\s*([^}]+?))?\s*\}/g;

function href(target: Target): string {
  return target.anchor === ''
    ? `/${target.route}`
    : `/${target.route}#${target.anchor}`;
}

/** Resolve `{@link name}` and `{@link name | label}`, then guard MDX syntax. */
function prose(text: string, index: SymbolIndex, place: Place): string {
  const resolved = text.replace(
    LINK,
    (_, target: string, label: string | undefined) => {
      const found = index.get(target);
      if (found === undefined) {
        if (place.scope === 'tea') {
          throw new Error(
            `${place.route}: {@link ${target}} names no documented symbol`,
          );
        }
        return code(label ?? target);
      }
      return `[${code(label ?? target)}](${href(found)})`;
    },
  );
  return escapeMdx(resolved);
}

/** A page description as plain text for front matter: no links, no code marks. */
function plainText(text: string): string {
  return text
    .replace(
      LINK,
      (_, target: string, label: string | undefined) => label ?? target,
    )
    .replaceAll('`', '');
}

/** A description inside another page, where links become code. */
function linkless(text: string): string {
  return escapeMdx(
    text.replace(LINK, (_, target: string, label: string | undefined) =>
      code(label ?? target),
    ),
  );
}

/**
 * Escape `<`, `{` and `}` outside code and formulas, where MDX would read JSX,
 * and `$` outside them, which would start math.
 */
function escapeMdx(markdown: string): string {
  return markdown
    .split(/(```[\s\S]*?```|`[^`\n]*`|^\$\$\n[\s\S]*?\n\$\$$)/gm)
    .map((part, index) =>
      index % 2 === 1
        ? part
        : part.replace(/[<{}$]/g, character => `\\${character}`),
    )
    .join('');
}

function cell(markdown: string): string {
  return markdown.replace(/\s*\n\s*/g, ' ').replace(/\|/g, '\\|');
}

function table(
  columns: readonly string[],
  rows: readonly (readonly string[])[],
): string {
  return [
    `| ${columns.join(' | ')} |`,
    `| ${columns.map(() => '---').join(' | ')} |`,
    ...rows.map(row => `| ${row.map(cell).join(' | ')} |`),
  ].join('\n');
}

function paramTable(
  params: readonly ParamRow[],
  index: SymbolIndex,
  page: Page,
): string {
  const typed = params.some(param => param.type !== null);
  const defaults = params.some(param => param.defaultValue !== null);
  return table(
    [
      page.paramLabel,
      ...(typed ? ['Type'] : []),
      ...(defaults ? ['Default'] : []),
      'Description',
    ],
    params.map(param => [
      code(param.name),
      ...(typed ? [param.type === null ? '' : code(param.type)] : []),
      ...(defaults
        ? [param.defaultValue === null ? '' : code(param.defaultValue)]
        : []),
      prose(param.description, index, page),
    ]),
  );
}

/** Overloads in one block; a long one lists a parameter per line. */
function signatureBlock(item: Entry, page: Page): string | undefined {
  if (item.signatures.length === 0) return undefined;
  const lines =
    page.language === 'tea'
      ? item.signatures.map(signature => wrapSignature(signature))
      : item.signatures;
  return fence(
    lines.join(lines.some(line => line.includes('\n')) ? '\n\n' : '\n'),
    page.language,
  );
}

/** One entry in reading order: summary, syntax, parameters, result, members, sections. */
function entryMarkdown(
  item: Entry,
  index: SymbolIndex,
  page: Page,
  heading?: string,
): string {
  return joinBlocks(
    heading,
    prose(item.summary, index, page),
    signatureBlock(item, page),
    item.params.length === 0 ? undefined : paramTable(item.params, index, page),
    item.returns === null
      ? undefined
      : `**Returns:** ${prose(item.returns, index, page)}`,
    item.table === null
      ? undefined
      : table(
          item.table.columns,
          item.table.rows.map(row =>
            row.map(value => prose(value, index, page)),
          ),
        ),
    prose(item.body, index, page),
  );
}

function frontMatter(title: string, description: string | null): string {
  return joinBlocks(
    `---\ntitle: ${JSON.stringify(title)}${description === null ? '' : `\ndescription: ${JSON.stringify(plainText(description))}`}\n---`,
    GENERATED,
  );
}

/**
 * A page's files by route: one file listing its entries under category
 * headings, or, for a per-entry page, a file listing them by category plus
 * one file for each entry, whose title is its name.
 */
function pageFiles(page: Page, index: SymbolIndex): [string, string][] {
  const grouped = categories(page);
  const intro = prose(page.intro, index, page);
  if (page.perEntry) {
    return [
      [
        page.route,
        joinBlocks(
          frontMatter(page.title, page.description),
          intro,
          ...[...grouped].map(([category, items]) =>
            joinBlocks(
              `## ${category}`,
              table(
                ['Name', 'Description'],
                items.map(item => [
                  `[${code(item.name)}](/${page.route}/${item.heading})`,
                  prose(item.summary, index, page),
                ]),
              ),
            ),
          ),
        ),
      ],
      ...page.entries.map(
        item =>
          [
            `${page.route}/${item.heading}`,
            joinBlocks(
              // The summary opens the body, so no description repeats it.
              frontMatter(item.name, null),
              entryMarkdown(item, index, page),
              item.members.length === 0
                ? undefined
                : joinBlocks(
                    '## Methods',
                    ...item.members.map(member =>
                      entryMarkdown(
                        member,
                        index,
                        page,
                        `### ${member.heading}`,
                      ),
                    ),
                  ),
            ),
          ] as [string, string],
      ),
    ];
  }
  const summaryTable =
    page.entries.length > 3
      ? table(
          ['Name', 'Description'],
          [...grouped.values()]
            .flat()
            .filter(item => item.heading !== '')
            .map(item => [
              `[${code(item.name)}](#${slug(item.heading)})`,
              prose(item.summary, index, page),
            ]),
        )
      : undefined;
  const shared =
    page.shared.length === 0
      ? undefined
      : `## Common parameters\n\n${paramTable(page.shared, index, page)}`;
  const sections = [...grouped].map(([category, items]) =>
    joinBlocks(
      `## ${category}`,
      ...items.map(item =>
        joinBlocks(
          entryMarkdown(
            item,
            index,
            page,
            item.heading === '' ? undefined : `### ${item.heading}`,
          ),
          ...item.members.map(member =>
            entryMarkdown(
              member,
              index,
              page,
              `#### ${memberHeading(page, item, member)}`,
            ),
          ),
        ),
      ),
    ),
  );
  return [
    [
      page.route,
      joinBlocks(
        frontMatter(page.title, page.description),
        intro,
        summaryTable,
        shared,
        ...sections,
      ),
    ],
  ];
}

// ---- generated articles -----------------------------------------------------

/** A generated page of prose: the reading guide, the A–Z index, Pine Script. */
interface Article {
  readonly route: string;
  readonly title: string;
  readonly description: string;
  /** Markdown whose `{@link}`s resolve like an entry's. */
  readonly markdown: string;
}

const READING_GUIDE = [
  '## Reading signatures',
  'A built-in reads `result name(qualifier type parameter, …)`. The result’s qualifier is shown only when it is fixed, as in `input int input.int(…)`; otherwise the result is as variable as the most variable argument. `= …` marks an optional parameter, whose description says what leaving it out means, and `...` marks one that takes any number of arguments. `int | float` accepts either type. Qualifiers go from least to most variable: `const`, `input`, `simple`, `series` (see [Types and qualifiers](/reference/language/types)).',
  'A function written in Tea, such as `ta.sma` or `trade.nextOpen`, shows its declaration as written: a parameter without a qualifier accepts any qualifier, a parameter without a type accepts any argument the function body can use, and **Returns** names the result type. Methods show their declarations, including the result type.',
  '## Reading formulas',
  'A formula names each value after the parameter it comes from, and a subscript names the bar. The current bar is t, so a value on the current bar and one i bars back read',
  '$$\nx_t = \\texttt{x} \\qquad x_{t-i} = \\texttt{x[i]}\n$$',
  'A value before the first bar is `na`. Each entry’s **Warm-up and na** says when its result is `na`.',
  '## How examples run',
  'Every example on these pages is a complete program, and the output under it is what the program writes when the reference is built. The program runs as',
  '```bash\ntea run example.tea --input example.csv\n```',
  'on the CSV shown with it, or on a single bar whose `time` is 0 when it shows none. The CSV holds only the columns the program reads, and an empty cell is `na`. Each output column is a value the program writes with `emit`, and `index` counts bars from 0. A strategy’s run also writes the broker’s event outputs, such as `broker.FillExecuted`; the examples show only the columns they write themselves.',
  'Examples are illustrations: they show what this version of Tea computes, not values checked against Pine Script.',
].join('\n\n');

/** How a script reaches each documented namespace. */
function namesAndImports(libraries: readonly TeaLibrary[]): string {
  const natives = [
    ...new Set(
      [...CATALOG.funcs.keys(), ...CATALOG.vars.keys()]
        .filter(name => name.includes('.'))
        .map(name => name.slice(0, name.indexOf('.'))),
    ),
  ].sort();
  return joinBlocks(
    '## Names and imports',
    table(
      ['Names', 'How a script reaches them'],
      [
        ...libraries.map(library => [
          library.access === 'global'
            ? library.exports
                .filter(
                  item => item.kind === 'function' || item.kind === 'value',
                )
                .map(item => code(item.name))
                .join(', ')
            : code(`${library.name}.*`),
          library.access === 'global'
            ? 'In every script, without an import or a namespace.'
            : library.access === 'namespace'
              ? `In every script, as ${code(`${library.name}.name`)}.`
              : `After ${code(`import ${library.name}`)}, as ${code(`${library.name}.name`)}.`,
        ]),
        [
          natives.map(name => code(`${name}.*`)).join(', '),
          'In every script, as `namespace.name`.',
        ],
      ],
    ),
  );
}

function overviewArticle(libraries: readonly TeaLibrary[]): Article {
  return {
    route: 'reference/overview',
    title: 'Reading the reference',
    description:
      'How to read signatures, formulas and examples, and how a script reaches each name.',
    markdown: joinBlocks(
      'The reference documents every name a Tea script can use, the language itself, the `tea` command and the JavaScript API. Each entry gives its syntax, parameters and result, and where they help, a formula, an example with its real output, and how it differs from Pine Script. To learn Tea, start with the Documentation tab.',
      READING_GUIDE,
      namesAndImports(libraries),
    ),
  };
}

/** The hand-written Language pages, which the reference tests hold to coverage. */
export const LANGUAGE_PAGES = [
  'lexical-structure',
  'types',
  'declarations',
  'expressions',
  'control-flow',
  'outputs',
] as const;

/** A link to where an entry is documented, labeled with its name. */
function entryLink(item: Entry, index: SymbolIndex): string {
  const target = index.get(
    item.symbols.includes(item.name) ? item.name : item.symbols[0]!,
  );
  if (target === undefined) throw new Error(`${item.name} is not documented`);
  return `[${code(item.name)}](${href(target)})`;
}

/** Every keyword, operator and comment form, as the Language pages head them. */
export const LANGUAGE_TOKENS: readonly string[] = [
  ...KEYWORDS,
  ...Object.values(Op),
  '=',
  ...Object.values(AssignOp),
  '?:',
  '[]',
  '.',
  '=>',
  'true',
  'false',
  'na',
  '//',
  '/* */',
  '/** */',
  '//@version',
];

const ENTRY_KINDS: Readonly<Record<EntryKind, string>> = {
  function: 'function',
  variable: 'variable',
  constant: 'constant',
  type: 'type',
  enum: 'enum',
  interface: 'interface',
  class: 'class',
  command: 'command',
};

/**
 * Every Tea name in one table, sorted ignoring case: entries, methods, and
 * the language's keywords and operators, each linked to where it is
 * documented.
 */
async function indexArticle(
  root: string,
  pages: readonly Page[],
  index: SymbolIndex,
): Promise<Article> {
  const rows: [string, string, string, string][] = [];
  for (const page of pages.filter(candidate => candidate.scope === 'tea')) {
    for (const item of page.entries) {
      if (item.heading === '') continue;
      rows.push([
        item.name,
        entryLink(item, index),
        ENTRY_KINDS[item.kind],
        linkless(item.summary),
      ]);
      for (const member of item.members) {
        rows.push([
          member.name,
          entryLink(member, index),
          'method',
          linkless(member.summary),
        ]);
      }
    }
  }
  const language = await Promise.all(
    LANGUAGE_PAGES.map(async name => ({
      name,
      headings: (
        await readFile(
          path.join(root, `docs/reference/language/${name}.md`),
          'utf8',
        )
      )
        .split('\n')
        .filter(line => line.startsWith('#'))
        .flatMap(line =>
          [...line.matchAll(/`([^`]+)`/g)].map(match => match[1]!),
        ),
    })),
  );
  for (const token of LANGUAGE_TOKENS) {
    const page = language.find(candidate => candidate.headings.includes(token));
    if (page === undefined) {
      throw new Error(`no Language page heading names ${token}`);
    }
    rows.push([
      token,
      `[${code(token)}](/reference/language/${page.name})`,
      (KEYWORDS as readonly string[]).includes(token) ? 'keyword' : 'syntax',
      '',
    ]);
  }
  const sorted = (tokens: boolean) =>
    rows
      .filter(
        ([, , kind]) => (kind === 'keyword' || kind === 'syntax') === tokens,
      )
      .sort(
        ([a], [b]) =>
          a.localeCompare(b, 'en', {sensitivity: 'base'}) || a.localeCompare(b),
      );
  return {
    route: 'reference/a-z',
    title: 'A–Z index',
    description: 'Every name and keyword a Tea script can use, in one list.',
    markdown: joinBlocks(
      '## Names',
      table(
        ['Name', 'Kind', 'Summary'],
        sorted(false).map(([, link, kind, summary]) => [link, kind, summary]),
      ),
      '## Keywords and operators',
      table(
        ['Token', 'Kind'],
        sorted(true).map(([, link, kind]) => [link, kind]),
      ),
    ),
  };
}

/** Pine Script differences from library notes, entries and staged parameters. */
function pineArticle(
  libraries: readonly TeaLibrary[],
  pages: readonly Page[],
  index: SymbolIndex,
): Article {
  const missing = libraries.flatMap(library =>
    library.doc?.pine == null
      ? []
      : [joinBlocks(`### ${library.name}`, library.doc.pine)],
  );
  const staged = [...CATALOG.funcs].flatMap(([name, overloads]) => {
    const params = [
      ...new Set(
        overloads.flatMap(overload =>
          overload.params
            .filter(param => param.availability === 'staged')
            .map(param => code(param.name)),
        ),
      ),
    ];
    return params.length === 0
      ? []
      : [[`[${code(name)}](${href(index.get(name)!)})`, params.join(', ')]];
  });
  const differences = pages
    .filter(page => page.scope === 'tea')
    .flatMap(page => page.entries.flatMap(item => [item, ...item.members]))
    .flatMap(item =>
      item.pine === null ? [] : [[entryLink(item, index), item.pine]],
    );
  return {
    route: 'reference/pine-compatibility',
    title: 'Pine Script compatibility',
    description:
      'What Tea does not have yet, and where it behaves differently from Pine Script v6.',
    markdown: joinBlocks(
      'Tea follows Pine Script v6: a name both have behaves the same way unless this page lists it. A Pine name missing from the [A–Z index](/reference/a-z) is not in Tea yet. Some differences are in the language itself:',
      [
        '- A collection is a value: assigning it or passing it to a function copies it, where Pine Script shares a reference (see [memory model](/memory-model)).',
        '- A request has no `lookahead` or `gaps` argument and never waits for a requested bar to close: each bar sees the newest requested bar that opened at or before it, so with completed daily data an intraday bar sees that day’s close (see [Request synchronization](/requests)).',
        '- A function called under a condition keeps its history only on the bars where it runs (see [values and control flow](/language-guide/values-and-control-flow)).',
        '- A function name is declared once: Tea has no overloading by parameter types or count, so a Pine library that overloads a name needs one untyped function or separate names (see [declarations](/reference/language/declarations#functions)).',
      ].join('\n'),
      missing.length === 0 ? undefined : joinBlocks('## Libraries', ...missing),
      staged.length === 0
        ? undefined
        : joinBlocks(
            '## Parameters not supported yet',
            'Tea accepts these Pine Script parameters by position but rejects any argument for them.',
            table(['Function', 'Parameters'], staged),
          ),
      differences.length === 0
        ? undefined
        : joinBlocks(
            '## Functions and values',
            table(['Name', 'In Tea'], differences),
          ),
    ),
  };
}

function articleFile(article: Article, index: SymbolIndex): string {
  return joinBlocks(
    frontMatter(article.title, article.description),
    prose(article.markdown, index, {route: article.route, scope: 'tea'}),
  );
}

// ---- navigation -------------------------------------------------------------

interface NavigationGroup {
  readonly group: string;
  /** The page a group opens, such as `ta`'s namespace page. */
  readonly root?: string;
  readonly pages: readonly (string | NavigationGroup)[];
}

interface DocsJson {
  readonly navigation: {
    readonly tabs: readonly {
      readonly tab: string;
      readonly groups: readonly NavigationGroup[];
    }[];
  };
}

async function referenceTab(root: string): Promise<readonly NavigationGroup[]> {
  const docs = JSON.parse(
    await readFile(path.join(root, 'docs/docs.json'), 'utf8'),
  ) as DocsJson;
  const tab = docs.navigation.tabs.find(
    candidate => candidate.tab === 'Reference',
  );
  if (tab === undefined) throw new Error('docs.json has no Reference tab');
  return tab.groups;
}

/**
 * The page that opens a group: its root, or a per-entry page listed first in
 * a section heading such as Technical analysis. A section has no root, since
 * Mintlify draws a top-level group with a root as an expandable item.
 */
function openingPage(
  group: NavigationGroup,
  generated: ReadonlyMap<string, Page>,
): string | undefined {
  const [first] = group.pages;
  return (
    group.root ??
    (typeof first === 'string' && generated.get(first)?.perEntry
      ? first
      : undefined)
  );
}

function frontMatterValue(text: string, key: string): string {
  const value = new RegExp(`^${key}:\\s*(.+?)\\s*$`, 'm').exec(text)?.[1] ?? '';
  return /^["']/.test(value)
    ? (JSON.parse(value.replace(/^'|'$/g, '"')) as string)
    : value;
}

/**
 * docs.json owns navigation; generation checks it. Every generated page is
 * listed exactly once, and a per-entry page opens a group (see
 * {@link openingPage}) whose other pages are one group per category, listing
 * its entry pages in order. A mismatch prints the `pages` the group needs.
 */
async function checkNavigation(
  root: string,
  pages: readonly Page[],
  articles: readonly Article[],
): Promise<void> {
  const generated = new Map(pages.map(page => [page.route, page]));
  const listed = new Set<string>();
  const list = (route: string) => {
    if (listed.has(route)) throw new Error(`docs.json lists ${route} twice`);
    listed.add(route);
  };
  const walk = (group: NavigationGroup) => {
    const opening = openingPage(group, generated);
    const page = opening === undefined ? undefined : generated.get(opening);
    if (opening !== undefined) list(opening);
    if (page?.perEntry) {
      const expected = [...categories(page)].map(([category, items]) => ({
        group: category,
        pages: items.map(item => `${page.route}/${item.heading}`),
      }));
      const listedCategories =
        group.root === undefined ? group.pages.slice(1) : group.pages;
      if (JSON.stringify(listedCategories) !== JSON.stringify(expected)) {
        throw new Error(
          `docs.json: the group opened by ${page.route} must list its entries by category:\n${JSON.stringify(expected, null, 2)}`,
        );
      }
      for (const route of expected.flatMap(category => category.pages)) {
        list(route);
      }
      return;
    }
    for (const item of group.pages) {
      if (typeof item !== 'string') {
        walk(item);
        continue;
      }
      list(item);
      if (generated.get(item)?.perEntry) {
        throw new Error(
          `docs.json: ${item} must open its group, as its root or a section's first page`,
        );
      }
      if (
        !generated.has(item) &&
        !articles.some(article => article.route === item) &&
        !existsSync(path.join(root, 'docs', `${item}.md`))
      ) {
        throw new Error(`docs.json lists missing page ${item}`);
      }
    }
  };
  for (const group of await referenceTab(root)) walk(group);
  const unlisted = [
    ...pages.map(page => page.route),
    ...articles.map(article => article.route),
  ].filter(route => !listed.has(route));
  if (unlisted.length > 0) {
    throw new Error(
      `docs.json does not list generated pages: ${unlisted.join(', ')}`,
    );
  }
}

// ---- in-app manual ----------------------------------------------------------

// The CLI and the JavaScript API stay on the site; the A–Z index repeats the
// manual's search.
const OUTSIDE_MANUAL = {
  groups: ['Tools', 'JavaScript API'],
  routes: ['reference/a-z'],
};

/**
 * The script-facing Reference as data for `tea/reference`: every top-level
 * group of docs.json's Reference tab but Tools and JavaScript API, in order.
 * A per-entry page is one manual page whose entries are each followed by
 * their methods; generated and hand-written prose pages are articles. Links
 * stay inside the manual or keep only their text (see {@link manualLinks}).
 */
async function manual(
  root: string,
  pages: readonly Page[],
  articles: readonly Article[],
  index: SymbolIndex,
): Promise<ReferenceManual> {
  const generated = new Map(pages.map(page => [page.route, page]));
  const groups: {title: string; routes: string[]}[] = [];
  const collect = (node: string | NavigationGroup, routes: string[]) => {
    const opening =
      typeof node === 'string' ? undefined : openingPage(node, generated);
    if (typeof node === 'string') {
      if (!OUTSIDE_MANUAL.routes.includes(node)) routes.push(node);
    } else if (opening !== undefined) {
      routes.push(opening);
    } else {
      for (const child of node.pages) collect(child, routes);
    }
  };
  for (const group of await referenceTab(root)) {
    if (OUTSIDE_MANUAL.groups.includes(group.group)) continue;
    const routes: string[] = [];
    collect(group, routes);
    if (routes.length > 0) groups.push({title: group.group, routes});
  }
  const routes = new Set(groups.flatMap(group => group.routes));
  // A link may name any symbol of an entry, such as `color.red` of `color.*`,
  // or an entry's own page, and leads to the entry.
  const entryOf = new Map<string, string>();
  const entryAt = new Map<string, string>();
  for (const route of routes) {
    for (const item of generated.get(route)?.entries ?? []) {
      for (const owned of [item, ...item.members]) {
        for (const symbol of owned.symbols) {
          entryOf.set(symbol, owned.name);
          const target = index.get(symbol);
          if (target !== undefined) entryAt.set(href(target), owned.name);
        }
      }
    }
  }
  const text = (markdown: string, from: string) =>
    manualLinks(markdown, from, routes, entryOf, entryAt);
  const article = async (route: string): Promise<ReferencePage> => {
    const made = articles.find(candidate => candidate.route === route);
    const source =
      made === undefined
        ? await readFile(path.join(root, 'docs', `${route}.md`), 'utf8')
        : undefined;
    return {
      kind: 'article',
      id: route,
      title:
        made?.title ??
        (frontMatterValue(source!, 'sidebarTitle') ||
          frontMatterValue(source!, 'title')),
      description:
        made?.description ?? frontMatterValue(source!, 'description'),
      markdown: text(
        made?.markdown ?? source!.replace(/^---\n[\s\S]*?\n---\n/, '').trim(),
        route,
      ),
    };
  };
  const entries = (page: Page): ReferencePage => {
    const parameter = (param: ParamRow): ReferenceParameter => ({
      ...param,
      description: text(param.description, page.route),
    });
    const referenceEntry = (item: Entry): ReferenceEntry => {
      if (item.kind === 'class' || item.kind === 'command') {
        throw new Error(`${page.route}: ${item.name} cannot be in the manual`);
      }
      return {
        id: item.name,
        symbols: item.symbols,
        kind: item.kind,
        category: item.category,
        summary: text(item.summary, page.route),
        signatures: item.signatures.map(signature => wrapSignature(signature)),
        parameters: item.params.map(parameter),
        returns: item.returns === null ? null : text(item.returns, page.route),
        members:
          item.table === null
            ? null
            : {
                columns: item.table.columns,
                rows: item.table.rows.map(row =>
                  row.map(value => text(value, page.route)),
                ),
              },
        body: text(item.body, page.route),
      };
    };
    return {
      kind: 'entries',
      id: page.route,
      title: page.title,
      description: text(page.description, page.route),
      intro: text(page.intro, page.route),
      commonParameters: page.shared.map(parameter),
      entries: page.entries.flatMap(item => [
        referenceEntry(item),
        ...item.members.map(referenceEntry),
      ]),
    };
  };
  return {
    groups: await Promise.all(
      groups.map(async group => ({
        title: group.title,
        pages: await Promise.all(
          group.routes.map(route => {
            const page = generated.get(route);
            return page === undefined ? article(route) : entries(page);
          }),
        ),
      })),
    ),
  };
}

/**
 * Links for the in-app manual: `{@link ta.sma}`, a link to an entry's page
 * and a link to a manual page become `#ta.sma` and `#reference/builtins/ta`,
 * which the host resolves inside the manual. A link to a page outside the
 * manual, such as a guide, or to a heading on the same page keeps only its
 * text; a link with a scheme stays.
 */
function manualLinks(
  markdown: string,
  from: string,
  routes: ReadonlySet<string>,
  entryOf: ReadonlyMap<string, string>,
  entryAt: ReadonlyMap<string, string>,
): string {
  return markdown
    .replace(LINK, (_, target: string, label: string | undefined) => {
      const id = entryOf.get(target);
      return id === undefined
        ? code(label ?? target)
        : `[${code(label ?? target)}](#${id})`;
    })
    .replace(
      /\[([^\]]+)\]\(([^)\s]+)\)/g,
      (whole, label: string, link: string) => {
        if (/^[a-z][a-z0-9+.-]*:/i.test(link)) return whole;
        // An entry link from above stays; an anchor to a heading on the same
        // page has nothing to point at in the manual.
        if (link.startsWith('#')) {
          return [...entryOf.values()].includes(link.slice(1)) ? whole : label;
        }
        const [target = '', anchor] = link.split('#');
        const route = target.startsWith('/')
          ? target.slice(1).replace(/\/$/, '')
          : path.posix
              .normalize(path.posix.join(path.posix.dirname(from), target))
              .replace(/\.md$/, '');
        const entry =
          entryAt.get(
            anchor === undefined ? `/${route}` : `/${route}#${anchor}`,
          ) ?? entryAt.get(`/${route}`);
        if (entry !== undefined) return `[${label}](#${entry})`;
        return routes.has(route) ? `[${label}](#${route})` : label;
      },
    );
}

// ---- outputs ----------------------------------------------------------------

function symbolIndex(
  pages: readonly Page[],
  scope: Page['scope'],
): Map<string, Target> {
  const index = new Map<string, Target>();
  for (const page of pages.filter(candidate => candidate.scope === scope)) {
    for (const [symbol, target] of targets(page)) {
      if (index.has(symbol)) {
        // One JavaScript declaration can be exported by several entry points;
        // links go to the first in package.json order.
        if (scope === 'javascript') continue;
        throw new Error(
          `${symbol} is documented on both ${index.get(symbol)!.route} and ${page.route}`,
        );
      }
      index.set(symbol, target);
    }
  }
  return index;
}

/**
 * Every example the Tea reference shows, with the entry it documents: the
 * natives' and every shipped library's, members included.
 */
function referenceExamples(
  libraries: readonly TeaLibrary[],
): [string, DocExample][] {
  const docs: [string, DocComment | null][] = [
    ...Object.keys(NATIVE_FUNCTION_DOCS).map(
      name => [name, nativeFunctionDocs(name)] as [string, DocComment | null],
    ),
    ...Object.keys(NATIVE_VALUE_DOCS).map(
      name => [name, nativeValueDocs(name)] as [string, DocComment | null],
    ),
    ...libraries.flatMap(library => [
      [`library ${library.name}`, library.doc] as [string, DocComment | null],
      ...library.exports.flatMap(item => [
        [qualifiedName(library, item.name), item.doc] as [
          string,
          DocComment | null,
        ],
        ...item.members.map(
          member =>
            [
              `${qualifiedName(library, item.name)}.${member.name}`,
              member.doc,
            ] as [string, DocComment | null],
        ),
      ]),
    ]),
  ];
  return docs.flatMap(([where, doc]) =>
    (doc?.examples ?? []).map(
      (example, index) =>
        [`${where} example ${index + 1}`, example] as [string, DocExample],
    ),
  );
}

/** Every generated reference file, keyed by its path. */
export async function referenceOutputs(
  root = ROOT,
): Promise<ReadonlyMap<string, string>> {
  const libraries = teaLibraries();
  const written = await runExamples(referenceExamples(libraries));
  const outputs: Outputs = doc =>
    doc.examples.map(example => written.get(exampleKey(example))!);
  const pages = [
    ...builtinPages(libraries, outputs),
    ...libraryPages(libraries, outputs),
    cliPage(),
    ...javascriptPages(),
  ];
  const indexes = {
    tea: symbolIndex(pages, 'tea'),
    javascript: symbolIndex(pages, 'javascript'),
  };
  const articles = [
    overviewArticle(libraries),
    await indexArticle(root, pages, indexes.tea),
    pineArticle(libraries, pages, indexes.tea),
  ];
  await checkNavigation(root, pages, articles);
  const file = (route: string) => path.join(root, 'docs', `${route}.md`);
  return new Map([
    [
      path.join(root, 'docs/assets/tea.tmLanguage.json'),
      JSON.stringify({...generateGrammar(), name: 'tea', displayName: 'Tea'}),
    ],
    [
      path.join(root, 'src/reference/manual.json'),
      JSON.stringify(await manual(root, pages, articles, indexes.tea)),
    ],
    ...articles.map(
      article =>
        [file(article.route), articleFile(article, indexes.tea)] as const,
    ),
    ...pages.flatMap(page =>
      pageFiles(page, indexes[page.scope]).map(
        ([route, markdown]) => [file(route), markdown] as const,
      ),
    ),
  ]);
}

/**
 * Turn site routes (`/requests`, `/reference/builtins/ta#tasma`) into links to
 * real sibling files, so the Markdown reads the same on the web and inside an
 * extracted package. A route without a page is an error.
 */
function portableLinks(content: string, file: string, root: string): string {
  return content.replace(
    /\]\(\/([^)#\s]*)(#[^)\s]*)?\)/g,
    (_, route: string, anchor = '') => {
      const target = path.join(root, 'docs', `${route.replace(/\/$/, '')}.md`);
      if (!existsSync(target) && !route.startsWith('reference/')) {
        throw new Error(
          `${path.relative(root, file)} links to missing page /${route}`,
        );
      }
      const relative = path
        .relative(path.dirname(file), target)
        .split(path.sep)
        .join('/');
      return `](${relative.startsWith('.') ? relative : `./${relative}`}${anchor})`;
    },
  );
}

async function generatedFiles(directory: string): Promise<string[]> {
  const found: string[] = [];
  for (const item of await readdir(directory, {withFileTypes: true})) {
    const file = path.join(directory, item.name);
    if (item.isDirectory()) found.push(...(await generatedFiles(file)));
    else if (
      item.name.endsWith('.md') &&
      (await readFile(file, 'utf8')).includes(GENERATED)
    ) {
      found.push(file);
    }
  }
  return found;
}

interface GenerateOptions {
  readonly root?: string;
  readonly check?: boolean;
  readonly report?: (message: string) => void;
}

/** Write the reference, or with `check` report every file that would change. */
export async function generateReference(
  options: GenerateOptions = {},
): Promise<boolean> {
  const root = options.root ?? ROOT;
  const check = options.check ?? false;
  const report = options.report ?? (message => console.error(message));
  let stale = false;
  const outputs = await referenceOutputs(root);
  for (const [file, content] of outputs) {
    const formatted = await format(
      path.extname(file) === '.json'
        ? content
        : portableLinks(content, file, root),
      {parser: path.extname(file) === '.json' ? 'json' : 'mdx'},
    );
    const current = existsSync(file) ? await readFile(file, 'utf8') : undefined;
    if (current === formatted) continue;
    if (check) {
      stale = true;
      report(`Generated reference is stale: ${path.relative(root, file)}`);
      continue;
    }
    await mkdir(path.dirname(file), {recursive: true});
    await writeFile(file, formatted, 'utf8');
  }
  for (const file of await generatedFiles(path.join(root, 'docs/reference'))) {
    if (outputs.has(file)) continue;
    if (check) {
      stale = true;
      report(
        `Generated reference page has no source: ${path.relative(root, file)}`,
      );
      continue;
    }
    await rm(file);
    // Drop directories the removed page leaves empty, up to docs/reference.
    for (
      let directory = path.dirname(file);
      directory !== path.join(root, 'docs/reference') &&
      (await readdir(directory)).length === 0;
      directory = path.dirname(directory)
    ) {
      await rm(directory, {recursive: true});
    }
  }
  if (!stale && check) console.log('Generated Tea reference is current.');
  return !stale;
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === SCRIPT_FILE
) {
  const current = await generateReference({
    check: process.argv.includes('--check'),
  });
  if (!current) process.exitCode = 1;
}
